"""Prompts 汇总入口"""
from .qa import SYSTEM_PROMPT, QA_USER_TEMPLATE, build_qa_messages, build_context_block
from .task_split import (
    TASK_SPLIT_SYSTEM, TASK_SPLIT_USER_TEMPLATE,
    TASK_MERGE_SYSTEM, TASK_MERGE_USER_TEMPLATE,
)
from .memory_refine import (
    SESSION_REFINE_SYSTEM, SESSION_REFINE_USER_TEMPLATE,
    USER_REFINE_SYSTEM, USER_REFINE_USER_TEMPLATE,
    USER_REFINE_INCREMENTAL_SYSTEM, USER_REFINE_INCREMENTAL_USER_TEMPLATE,
)
from .agent import AGENT_SYSTEM_PROMPT, build_agent_messages
from .query_transform import (
    REWRITE_SYSTEM, REWRITE_USER_TEMPLATE,
    DECOMPOSE_SYSTEM, DECOMPOSE_USER_TEMPLATE,
)

__all__ = [
    'SYSTEM_PROMPT', 'QA_USER_TEMPLATE', 'build_qa_messages', 'build_context_block',
    'TASK_SPLIT_SYSTEM', 'TASK_SPLIT_USER_TEMPLATE',
    'TASK_MERGE_SYSTEM', 'TASK_MERGE_USER_TEMPLATE',
    'SESSION_REFINE_SYSTEM', 'SESSION_REFINE_USER_TEMPLATE',
    'USER_REFINE_SYSTEM', 'USER_REFINE_USER_TEMPLATE',
    'USER_REFINE_INCREMENTAL_SYSTEM', 'USER_REFINE_INCREMENTAL_USER_TEMPLATE',
    'AGENT_SYSTEM_PROMPT', 'build_agent_messages',
    'REWRITE_SYSTEM', 'REWRITE_USER_TEMPLATE',
    'DECOMPOSE_SYSTEM', 'DECOMPOSE_USER_TEMPLATE',
]
