# Generated by Django 5.2 on 2026-08-01 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_round', models.IntegerField(default=1, verbose_name='调用轮次')),
                ('tool_name', models.CharField(db_index=True, max_length=50, verbose_name='工具名称')),
                ('tool_args', models.JSONField(blank=True, default=dict, verbose_name='工具参数')),
                ('tool_result', models.TextField(blank=True, default='', verbose_name='工具结果')),
                ('call_id', models.CharField(blank=True, default='', max_length=100, verbose_name='调用ID')),
                ('result_ok', models.BooleanField(default=True, verbose_name='是否成功')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('qa_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_traces', to='chat.qarecord', verbose_name='问答记录')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memory.session', verbose_name='会话')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent调用链',
                'verbose_name_plural': 'Agent调用链',
                'db_table': 'agent_trace',
                'ordering': ['qa_record_id', 'tool_round', 'id'],
                'indexes': [models.Index(fields=['qa_record_id', 'tool_round'], name='idx_agent_qa_round')],
            },
        ),
    ]
