# Generated by Django 5.2 on 2026-08-09 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('chat', '0003_alter_hotqacache_visibility_scope'),
        ('memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='原始问题')),
                ('definition', models.JSONField(blank=True, default=list, verbose_name='节点DAG定义')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('running', '执行中'), ('waiting_approval', '等待人工确认'), ('succeeded', '成功'), ('failed', '失败'), ('degraded', '降级完成')], db_index=True, default='planning', max_length=24, verbose_name='状态')),
                ('max_nodes', models.IntegerField(default=10, verbose_name='最大节点数')),
                ('max_duration_sec', models.IntegerField(default=300, verbose_name='最大时长(秒)')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('qa_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.qarecord', verbose_name='问答记录')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memory.session', verbose_name='会话')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent工作流',
                'verbose_name_plural': 'Agent工作流',
                'db_table': 'agent_workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64, verbose_name='节点ID')),
                ('node_name', models.CharField(blank=True, default='', max_length=128, verbose_name='节点名称')),
                ('step_type', models.CharField(db_index=True, max_length=32, verbose_name='节点类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('succeeded', '成功'), ('failed', '失败'), ('blocked', '等待人工确认'), ('approved', '已批准'), ('rejected', '已拒绝'), ('skipped', '已跳过')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('attempt', models.IntegerField(default=1, verbose_name='重试次数')),
                ('input', models.JSONField(blank=True, default=dict, verbose_name='输入')),
                ('output', models.JSONField(blank=True, default=dict, verbose_name='输出')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('ticket_id', models.BigIntegerField(blank=True, null=True, verbose_name='审批工单ID')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='agent.agentworkflow', verbose_name='工作流')),
            ],
            options={
                'verbose_name': '工作流节点',
                'verbose_name_plural': '工作流节点',
                'db_table': 'agent_workflow_node',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='agentworkflow',
            index=models.Index(fields=['user', '-created_at'], name='idx_wf_user_time'),
        ),
        migrations.AddIndex(
            model_name='agentworkflow',
            index=models.Index(fields=['status', '-created_at'], name='idx_wf_status_time'),
        ),
        migrations.AddIndex(
            model_name='agentworkflow',
            index=models.Index(fields=['qa_record'], name='idx_wf_qa'),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['workflow', 'status'], name='idx_wfnode_wf_status'),
        ),
        migrations.AlterUniqueTogether(
            name='workflownoderun',
            unique_together={('workflow', 'node_id')},
        ),
    ]
