# Generated by Django 5.2 on 2026-08-01 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpBlacklist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(choices=[('login_fail', '登录连续失败'), ('manual', '人工封禁'), ('bot', '爬虫/机器人')], default='manual', max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=256)),
                ('fail_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='过期时间，NULL 表示永久', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_ip_blacklist',
                'indexes': [models.Index(fields=['ip', 'is_active'], name='idx_bl_ip_active'), models.Index(fields=['expires_at'], name='idx_bl_expires')],
            },
        ),
        migrations.CreateModel(
            name='IpWhitelist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_or_cidr', models.CharField(help_text='单 IP 或 CIDR，如 10.0.0.0/8', max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_ip_whitelist',
            },
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(choices=[('phone', '手机号'), ('id_card', '身份证'), ('email', '邮箱'), ('bank_card', '银行卡'), ('secret', '内部机密'), ('other', '其它')], default='other', max_length=16)),
                ('action', models.CharField(choices=[('mask', '脱敏'), ('block', '拦截'), ('warn', '仅告警')], default='mask', max_length=8)),
                ('is_regex', models.BooleanField(default=False, help_text='是否作为正则处理')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_sensitive_word_list',
                'indexes': [models.Index(fields=['category', 'is_enabled'], name='idx_sw_cat_enable')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('result', models.CharField(choices=[('success', 'success'), ('wrong_password', 'wrong_password'), ('user_not_found', 'user_not_found'), ('locked', 'locked'), ('captcha_fail', 'captcha_fail'), ('ip_denied', 'ip_denied')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_login_attempt_record',
                'indexes': [models.Index(fields=['ip', '-created_at'], name='idx_la_ip_time'), models.Index(fields=['username', '-created_at'], name='idx_la_user_time'), models.Index(fields=['result'], name='idx_la_result')],
            },
        ),
    ]
