# Generated by Django 5.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitiveword',
            name='hit_count',
            field=models.IntegerField(default=0, help_text='累计命中次数（审查器 Redis 计数落库，管理端展示）'),
        ),
    ]
