# Generated by Django 5.2 on 2026-07-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipblacklist',
            table='security_ip_blacklist',
        ),
        migrations.AlterModelTable(
            name='ipwhitelist',
            table='security_ip_whitelist',
        ),
        migrations.AlterModelTable(
            name='loginattempt',
            table='security_login_attempt_record',
        ),
        migrations.AlterModelTable(
            name='sensitiveword',
            table='security_sensitive_word_list',
        ),
    ]
