# Generated by Django 5.2 on 2026-08-04 18:02

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # 依赖 pgvector 扩展安装迁移：graph_entity 含 vector 字段，
        # 必须先于 users.0007_install_pgvector 之后的表创建（否则新库建表失败）
        ('users', '0007_install_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphCommunity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('community_id', models.IntegerField(db_index=True)),
                ('level', models.SmallIntegerField(default=0, help_text='社区粒度：0=细 1=中 2=粗')),
                ('entity_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None)),
                ('summary', models.TextField(blank=True, default='')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'graph_community',
                'indexes': [models.Index(fields=['community_id', 'level'], name='idx_gc_id_level')],
            },
        ),
        migrations.CreateModel(
            name='GraphEntity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('type', models.CharField(choices=[('PERSON', '人物'), ('ORG', '组织'), ('CONCEPT', '概念'), ('TERM', '术语'), ('PRODUCT', '产品')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_doc_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='实体语义向量（BGE-M3 1024 维）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'graph_entity',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_ge_embedding_hnsw', opclasses=['vector_cosine_ops']), models.Index(fields=['type'], name='idx_ge_type')],
            },
        ),
        migrations.CreateModel(
            name='GraphRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(db_index=True, max_length=64)),
                ('weight', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_doc_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_entity', models.ForeignKey(db_column='source_entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='graph.graphentity')),
                ('target_entity', models.ForeignKey(db_column='target_entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='graph.graphentity')),
            ],
            options={
                'db_table': 'graph_relation',
                'indexes': [models.Index(fields=['source_entity', 'relation_type'], name='idx_gr_source_rel'), models.Index(fields=['target_entity', 'relation_type'], name='idx_gr_target_rel')],
                'unique_together': {('source_entity', 'target_entity', 'relation_type')},
            },
        ),
    ]
