# Generated by Django 5.2 on 2026-07-15 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('task_name', models.CharField(max_length=128)),
                ('queue', models.CharField(default='default', max_length=32)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('success', 'success'), ('failure', 'failure'), ('retry', 'retry'), ('revoked', 'revoked')], default='pending', max_length=16)),
                ('result', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'celery_task_log',
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_ctl_status'), models.Index(fields=['task_name'], name='idx_ctl_name')],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.TextField(default='')),
                ('value_type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('bool', 'bool'), ('json', 'json')], default='string', max_length=8)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('is_secret', models.BooleanField(default=False, help_text='加密存储的敏感项')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_config',
            },
        ),
        migrations.CreateModel(
            name='DataExportLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('export_type', models.CharField(help_text='qa_records/audit/users/documents', max_length=32)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('file_size', models.BigIntegerField(default=0)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_export_log',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_del_user_time')],
            },
        ),
        migrations.CreateModel(
            name='LlmCallLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(default='deepseek', max_length=32)),
                ('model', models.CharField(default='deepseek-chat', max_length=64)),
                ('scene', models.CharField(default='qa', help_text='qa/task_split/memory_refine/embedding/rerank', max_length=32)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_call_log',
                'indexes': [models.Index(fields=['provider', 'model', '-created_at'], name='idx_llm_pm_time'), models.Index(fields=['scene'], name='idx_llm_scene')],
            },
        ),
    ]
