# Generated by Django 5.2 on 2026-07-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='celerytasklog',
            table='system_celery_task_log',
        ),
        migrations.AlterModelTable(
            name='dataexportlog',
            table='system_data_export_log',
        ),
        migrations.AlterModelTable(
            name='llmcalllog',
            table='system_llm_call_log',
        ),
    ]
