# Generated by Django 5.2 on 2026-08-03 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='category',
            field=models.CharField(choices=[('llm', 'llm'), ('embedding', 'embedding'), ('retrieval', 'retrieval'), ('storage', 'storage'), ('email', 'email'), ('agent', 'agent'), ('security', 'security'), ('memory', 'memory'), ('analytics', 'analytics'), ('eval', 'eval')], default='llm', help_text='配置分组，用于前端按 tab 展示', max_length=16),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='is_readonly',
            field=models.BooleanField(default=False, help_text='只读项，前端不可改，需改 .env'),
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['category'], name='idx_sc_category'),
        ),
    ]
