# Generated by Django 5.2 on 2026-08-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_config_category_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='label',
            field=models.CharField(blank=True, default='', help_text='中文名，前端主标题', max_length=64),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='description',
            field=models.CharField(blank=True, default='', help_text='详细说明/选项解释', max_length=256),
        ),
    ]
