# Generated by Django 5.2 on 2026-08-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_config_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='options',
            field=models.TextField(blank=True, default='', help_text='可选值列表 JSON，空=自由输入'),
        ),
    ]
