# Generated by Django 5.2 on 2026-08-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_config_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='单位，前端在控件后显示', max_length=8),
        ),
    ]
