# Generated by Django 5.2 on 2026-08-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_config_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='显示名称')),
                ('provider', models.CharField(help_text='如 deepseek、openai', max_length=32, verbose_name='提供商')),
                ('model_type', models.CharField(choices=[('llm', 'LLM 对话模型'), ('embedding', 'Embedding 向量模型'), ('rerank', 'Rerank 重排序模型')], max_length=16, verbose_name='模型类型')),
                ('base_url', models.URLField(blank=True, default='', max_length=256, verbose_name='API 地址')),
                ('model_name', models.CharField(help_text='如 deepseek-chat', max_length=128, verbose_name='模型标识')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '模型配置',
                'verbose_name_plural': '模型配置',
                'db_table': 'system_llm_model',
                'ordering': ['model_type', 'name'],
                'unique_together': {('model_type', 'name')},
            },
        ),
    ]
