# Generated by Django 5.2 on 2026-08-03 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_llm_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='risk_level',
            field=models.CharField(choices=[('normal', '普通'), ('high', '高风险')], default='normal', help_text='风险等级，高风险项需超管复核', max_length=8),
        ),
        migrations.CreateModel(
            name='ConfigChangeTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('config_key', models.CharField(max_length=64, verbose_name='配置项')),
                ('config_label', models.CharField(blank=True, default='', max_length=64, verbose_name='配置项中文名')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='原值')),
                ('new_value', models.TextField(verbose_name='新值')),
                ('risk_level', models.CharField(choices=[('normal', '普通'), ('high', '高风险')], default='normal', max_length=8, verbose_name='风险等级')),
                ('reason', models.CharField(blank=True, default='', max_length=256, verbose_name='变更原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('first_approved', '待超管复核'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=16, verbose_name='状态')),
                ('review_comment', models.CharField(blank=True, default='', max_length=256, verbose_name='审批意见')),
                ('super_admin_comment', models.CharField(blank=True, default='', max_length=256, verbose_name='超管审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('super_admin_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='超管复核时间')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_config_tickets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_config_tickets', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('super_admin_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_admin_reviewed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='超管复核人')),
            ],
            options={
                'verbose_name': '配置变更工单',
                'verbose_name_plural': '配置变更工单',
                'db_table': 'system_config_ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
