# Generated by Django 5.2 on 2026-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_config_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='timeout',
            field=models.IntegerField(blank=True, help_text='为空时回退到全局 LLM_TIMEOUT', null=True, verbose_name='超时秒数'),
        ),
    ]
