# Generated by Django 5.2 on 2026-08-04 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_ticket_change_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChangeTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_model_snapshot', models.JSONField(default=dict, help_text='工单创建时的模型完整数据，防止目标模型被他人先改', verbose_name='模型快照')),
                ('operation', models.CharField(choices=[('update_normal', '修改普通字段'), ('deactivate', '停用模型'), ('delete', '删除模型')], max_length=20, verbose_name='操作类型')),
                ('changed_fields', models.JSONField(blank=True, default=dict, verbose_name='变更字段')),
                ('dependency_refs', models.JSONField(blank=True, default=list, help_text='被哪些配置项引用，空列表=无依赖', verbose_name='依赖引用')),
                ('risk_level', models.CharField(choices=[('normal', '普通'), ('high', '高风险')], default='normal', max_length=8, verbose_name='风险等级')),
                ('reason', models.CharField(blank=True, default='', max_length=256, verbose_name='变更原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('first_approved', '待超管复核'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=16, verbose_name='状态')),
                ('review_comment', models.CharField(blank=True, default='', max_length=256, verbose_name='审批意见')),
                ('super_admin_comment', models.CharField(blank=True, default='', max_length=256, verbose_name='超管审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('super_admin_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='超管复核时间')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_tickets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_model_tickets', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('super_admin_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_admin_reviewed_model_tickets', to=settings.AUTH_USER_MODEL, verbose_name='超管复核人')),
                ('target_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_tickets', to='system.llmmodel', verbose_name='目标模型')),
            ],
            options={
                'verbose_name': '模型变更工单',
                'verbose_name_plural': '模型变更工单',
                'db_table': 'system_model_ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
