# Generated by Django 5.2 on 2026-08-07 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_remove_production_eval_metric_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('config', '配置变更'), ('schedule', '定时任务'), ('model', '模型变更')], max_length=16, verbose_name='工单类型')),
                ('operation', models.CharField(choices=[('modify', '修改'), ('update_normal', '修改模型'), ('deactivate', '停用模型'), ('delete', '删除模型')], max_length=20, verbose_name='操作类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('pending_review', '待复核'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=16, verbose_name='状态')),
                ('risk_level', models.CharField(choices=[('normal', '普通'), ('high', '高风险')], default='normal', max_length=8, verbose_name='风险等级')),
                ('reason', models.CharField(blank=True, default='', max_length=256, verbose_name='变更原因')),
                ('audit_comment', models.CharField(blank=True, default='', max_length=256, verbose_name='审核意见')),
                ('review_comment', models.CharField(blank=True, default='', max_length=256, verbose_name='复核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('audited_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('config_key', models.CharField(blank=True, max_length=64, null=True, verbose_name='配置项')),
                ('target_model_id', models.BigIntegerField(blank=True, null=True, verbose_name='目标模型ID')),
                ('detail', models.JSONField(default=dict, verbose_name='业务详情')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_tickets', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'system_ticket',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket_type', 'status'], name='system_tick_ticket__c8b6ef_idx'), models.Index(fields=['creator', 'status'], name='system_tick_creator_9fd56d_idx'), models.Index(fields=['config_key'], name='system_tick_config__32a50f_idx'), models.Index(fields=['target_model_id'], name='system_tick_target__5edd55_idx')],
            },
        ),
    ]
