# Generated by Django 5.2 on 2026-08-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_migrate_data_to_ticket'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configchangeticket',
            table='system_config_ticket_backup',
        ),
        migrations.AlterModelTable(
            name='modelchangeticket',
            table='system_model_ticket_backup',
        ),
    ]
