# Generated by Django 5.2 on 2026-08-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_rename_old_ticket_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelchangeticket',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='modelchangeticket',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='modelchangeticket',
            name='super_admin_reviewer',
        ),
        migrations.RemoveField(
            model_name='modelchangeticket',
            name='target_model',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='auditor',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='ConfigChangeTicket',
        ),
        migrations.DeleteModel(
            name='ModelChangeTicket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
