# Generated by Django 5.2 on 2026-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_remove_modelchangeticket_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='category',
            field=models.CharField(choices=[('llm', 'llm'), ('embedding', 'embedding'), ('retrieval', 'retrieval'), ('storage', 'storage'), ('email', 'email'), ('agent', 'agent'), ('security', 'security'), ('memory', 'memory'), ('analytics', 'analytics'), ('eval', 'eval'), ('knowledge', 'knowledge')], default='llm', help_text='配置分组，用于前端按 tab 展示', max_length=16),
        ),
    ]
