# Generated by Django 5.2 on 2026-07-25 08:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMemory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='记忆键，如 "company_rules"', max_length=64, unique=True)),
                ('content', models.TextField(help_text='记忆内容，直接拼进 System Prompt')),
                ('scope_root_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='作用于哪些根类型；空表示 all', size=None)),
                ('priority', models.IntegerField(default=0, help_text='数值越大优先级越高')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'memory_global_memory',
                'indexes': [models.Index(fields=['is_enabled', '-priority'], name='idx_gm_enable_pri')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='新会话', max_length=256)),
                ('root_type', models.CharField(default='company_doc', help_text='会话默认的知识库根类型', max_length=32)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('turn_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memory_session',
            },
        ),
        migrations.CreateModel(
            name='SessionMemory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(default='', help_text='会话主题一句话摘要')),
                ('entities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='关键实体：人名/产品名/项目名', size=None)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('turn_refined', models.IntegerField(default=0, help_text='上次提炼时的轮次')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='memory.session')),
            ],
            options={
                'db_table': 'memory_session_memory',
            },
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='偏好：{tone:"专业", length:"简洁", ...}')),
                ('domain_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='用户擅长/关心的领域', size=None)),
                ('frequent_topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='高频问的主题', size=None)),
                ('profile_text', models.TextField(default='', help_text='拼装成 Prompt 用的画像文本')),
                ('session_refined_count', models.IntegerField(default=0, help_text='被提炼过多少次会话')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memory_user_memory',
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', '-last_active_at'], name='idx_sess_user_act'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_archived'], name='idx_sess_archived'),
        ),
    ]
