# Generated by Django 5.2 on 2026-07-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='globalmemory',
            table='memory_global_memory',
        ),
        migrations.AlterModelTable(
            name='session',
            table='memory_session',
        ),
        migrations.AlterModelTable(
            name='sessionmemory',
            table='memory_session_memory',
        ),
        migrations.AlterModelTable(
            name='usermemory',
            table='memory_user_memory',
        ),
    ]
