# Generated by Django 5.2 on 2026-07-23 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_alter_globalmemory_table_alter_session_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmemory',
            name='scope_root_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='作用于哪些根类型；空表示 all', size=None),
        ),
    ]
