# Generated by Django 5.2 on 2026-08-01 13:10

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dept_id', models.BigIntegerField(blank=True, help_text='归属部门 ID（部门归属或团队归属冗余）', null=True)),
                ('team_id', models.BigIntegerField(blank=True, help_text='归属团队 ID（团队归属必填，部门归属为空）', null=True)),
                ('visibility_level', models.CharField(choices=[('TEAM_ONLY', '仅团队'), ('DEPT_ONLY', '仅部门'), ('PUBLIC', '全局公开')], default='TEAM_ONLY', help_text='可见性层级：TEAM_ONLY/DEPT_ONLY/PUBLIC', max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=256)),
                ('file_type', models.CharField(choices=[('pdf', 'pdf'), ('docx', 'docx'), ('markdown', 'markdown'), ('txt', 'txt'), ('code', 'code'), ('config', 'config'), ('other', 'other')], max_length=16)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(help_text='sha256 文件内容哈希，用于版本识别', max_length=64)),
                ('file_path', models.CharField(blank=True, default='', help_text='本地存储路径或 OSS URL', max_length=512)),
                ('mime_type', models.CharField(blank=True, default='', max_length=64)),
                ('has_block_user', models.BooleanField(default=False, help_text='是否有黑名单用户（加速检索跳过黑名单查询）')),
                ('has_resource_share', models.BooleanField(default=False, help_text='是否有跨范围共享（加速检索跳过共享查询）')),
                ('allow_download', models.BooleanField(default=False, help_text='是否允许下载该文档')),
                ('allow_share', models.BooleanField(default=False, help_text='是否允许分享该文档')),
                ('allow_share_request', models.BooleanField(default=False, help_text='是否允许他人发起分享申请')),
                ('preview_content', models.BooleanField(default=False, help_text='申请预览时是否允许查看正文')),
                ('preview_chunks', models.BooleanField(default=False, help_text='申请预览时是否允许查看切片')),
                ('secret_level', models.SmallIntegerField(choices=[(1, '普通'), (2, '内部'), (3, '机密'), (4, '绝密')], default=1, help_text='密级 1普通~4绝密，4禁止 PUBLIC')),
                ('audit_status', models.CharField(choices=[('pending_team', '待团队组长审核'), ('pending_compliance', '待合规复核'), ('rejected', '审核驳回'), ('passed', '双审通过'), ('archived', '归档'), ('deleted', '逻辑删除')], default='pending_team', max_length=32)),
                ('root_type', models.CharField(help_text='冗余：根节点类型，加速检索过滤', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('parsing', 'parsing'), ('desensitizing', 'desensitizing'), ('chunking', 'chunking'), ('embedding', 'embedding'), ('embedding_failed', 'embedding_failed'), ('done', 'done'), ('failed', 'failed')], default='pending', help_text='处理状态: pending/parsing/.../done/failed', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('chunk_count', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('version_tag', models.CharField(blank=True, default='', help_text='版本标签，如 v1.0、v2.1', max_length=64)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_time', models.DateTimeField(blank=True, help_text='逻辑删除时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restored_at', models.DateTimeField(blank=True, help_text='恢复时间（用于审计追溯）', null=True)),
                ('owner', models.ForeignKey(db_column='owner_id', help_text='文档 Owner', on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, db_column='restored_by', help_text='恢复人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(help_text='文档内切片序号，从 0 开始')),
                ('chunk_type', models.CharField(choices=[('text', 'text'), ('table', 'table'), ('image', 'image'), ('code', 'code'), ('config', 'config')], default='text', max_length=16)),
                ('content', models.TextField(help_text='切片原文')),
                ('content_length', models.IntegerField(default=0)),
                ('section_path', models.CharField(blank=True, default='', help_text='如 "第一章>1.1 节>表 1-2"', max_length=512)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('image_id', models.BigIntegerField(blank=True, help_text='若 chunk_type=image，关联 image_resource.id', null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'db_table': 'knowledge_document_chunk',
            },
        ),
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(default='python', max_length=32)),
                ('symbol_type', models.CharField(choices=[('function', 'function'), ('class', 'class'), ('method', 'method'), ('module', 'module'), ('variable', 'variable')], max_length=16)),
                ('symbol_name', models.CharField(max_length=128)),
                ('signature', models.TextField(blank=True, default='', help_text='函数签名，如 def foo(a:int)->str')),
                ('params', models.JSONField(blank=True, default=list, help_text='参数列表 [{name,type,default}]')),
                ('docstring', models.TextField(blank=True, default='')),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('parent_symbol', models.CharField(blank=True, default='', help_text='所属类名，用于方法', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='code_chunks', to='knowledge.document')),
                ('chunk', models.ForeignKey(db_column='chunk_id', on_delete=django.db.models.deletion.CASCADE, related_name='code_meta', to='knowledge.documentchunk')),
            ],
            options={
                'db_table': 'knowledge_code_chunk',
            },
        ),
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('storage_mode', models.CharField(choices=[('base64', 'base64'), ('oss', 'oss')], default='base64', max_length=8)),
                ('base64_data', models.TextField(blank=True, default='', help_text='当 storage_mode=base64 时存储')),
                ('oss_url', models.CharField(blank=True, default='', help_text='当 storage_mode=oss 时存储', max_length=512)),
                ('mime_type', models.CharField(default='image/png', max_length=32)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('size_bytes', models.IntegerField(default=0)),
                ('ocr_text', models.TextField(blank=True, default='', help_text='OCR 结果，便于图片检索')),
                ('caption', models.TextField(blank=True, default='', help_text='图片说明/图注')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='knowledge.document')),
            ],
            options={
                'db_table': 'knowledge_image',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('root_type', models.CharField(help_text='根节点类型，加速检索过滤', max_length=32)),
                ('node_type', models.CharField(choices=[('root', 'root'), ('folder', 'folder'), ('leaf', 'leaf')], default='folder', max_length=16)),
                ('node_level', models.SmallIntegerField(default=4, help_text='节点层级: 1=kb 2=dept 3=team 4+=业务分类')),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(default='/', help_text='路径枚举 /kb_id/dept_id/team_id/cat_id/... 首尾加 /', max_length=512)),
                ('depth', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('order_no', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ref_id', models.BigIntegerField(blank=True, help_text='关联源对象 ID：node_level=2 存 dept.id，node_level=3 存 team.id', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nodes', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, db_column='owner_user_id', help_text='节点 Owner，默认创建人，可作为节点级共享审批人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_node',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='node',
            field=models.ForeignKey(db_column='node_id', help_text='挂载节点（团队/部门/业务分类节点均可）', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='knowledge.knowledgenode'),
        ),
        migrations.CreateModel(
            name='DocOperationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('doc_create', '上传文档'), ('doc_delete', '删除文档'), ('doc_visibility_change', '修改可见范围'), ('doc_download', '下载文档'), ('doc_reparse', '重新解析'), ('doc_restore', '恢复文档'), ('doc_set_active', '切换活跃版本'), ('node_create', '创建节点'), ('node_update', '修改节点'), ('node_delete', '删除节点'), ('doc_audit_team_pass', '团队审核通过'), ('doc_audit_team_reject', '团队审核驳回'), ('doc_audit_compliance_pass', '合规复核通过'), ('doc_audit_compliance_reject', '合规复核驳回'), ('doc_archive', '归档文档'), ('doc_physical_destroy', '物理销毁')], db_index=True, max_length=32)),
                ('operator_name', models.CharField(blank=True, default='', max_length=128)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='操作详情，如变更前后的值、目标用户等')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator', models.ForeignKey(blank=True, db_column='operator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.document')),
                ('node', models.ForeignKey(blank=True, db_column='node_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_doc_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceBlockList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('KNOWLEDGE_BASE', '知识库'), ('KNOWLEDGE_NODE', '知识节点'), ('DOCUMENT', '文档')], help_text='KNOWLEDGE_BASE/KNOWLEDGE_NODE/DOCUMENT', max_length=32)),
                ('resource_id', models.BigIntegerField(help_text='资源 ID：kb_id/node_id/doc_id')),
                ('block_inherit_mode', models.CharField(choices=[('ALL_DESCENDANTS', '本节点及所有后代'), ('NODE_ONLY', '仅本节点')], default='ALL_DESCENDANTS', help_text='节点级专属：ALL_DESCENDANTS=子树拉黑/NODE_ONLY=仅本节点', max_length=16)),
                ('reason', models.TextField(help_text='拉黑理由（必填，文本审计），如「已离职」「涉密项目剔除」')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('effective_from', models.DateTimeField(blank=True, help_text='NULL = 立即生效', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL = 永久封禁；可设临时封禁（如 7 天后自动解封）', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', '生效中'), ('EXPIRED', '已过期'), ('REVOKED', '已撤销')], default='ACTIVE', help_text='ACTIVE=封禁中/EXPIRED=到期自动解封/REVOKED=管理员手动解封', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_by', models.ForeignKey(blank=True, help_text='操作人（Owner 或管理员）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('blocked_user', models.ForeignKey(help_text='被封禁个人 user_id（唯一支持作用域 = 个人）', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_resources', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, help_text='解封人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '资源黑名单',
                'db_table': 'resource_block_list',
            },
        ),
        migrations.CreateModel(
            name='ResourceShare',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('KNOWLEDGE_BASE', '知识库'), ('KNOWLEDGE_NODE', '知识节点'), ('DOCUMENT', '文档')], help_text='KNOWLEDGE_BASE/KNOWLEDGE_NODE/DOCUMENT', max_length=32)),
                ('resource_id', models.BigIntegerField(help_text='资源 ID：kb_id/node_id/doc_id（逻辑外键）')),
                ('share_scope_type', models.CharField(choices=[('DEPT', '部门'), ('TEAM', '团队'), ('USER', '个人')], help_text='共享对象类型：DEPT/TEAM/USER', max_length=16)),
                ('share_scope_id', models.BigIntegerField(help_text='共享对象 ID：dept_id/team_id/user_id')),
                ('access_level', models.CharField(choices=[('READ', '只读'), ('EDIT', '可编辑')], default='READ', help_text='READ/EDIT', max_length=8)),
                ('inherit_mode', models.CharField(choices=[('ALL_DESCENDANTS', '本节点及所有后代'), ('NODE_ONLY', '仅本节点')], default='ALL_DESCENDANTS', help_text='节点级专属：ALL_DESCENDANTS=子树继承/NODE_ONLY=仅本节点', max_length=16)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('effective_from', models.DateTimeField(blank=True, help_text='NULL = 立即生效', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL = 永久有效', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', '生效中'), ('EXPIRED', '已过期'), ('REVOKED', '已撤销')], default='ACTIVE', help_text='ACTIVE/EXPIRED/REVOKED', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='授予人（Owner 或管理员）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, help_text='撤销人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '资源共享',
                'db_table': 'resource_share',
            },
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document'], name='idx_chunk_doc'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_type'], name='idx_chunk_type'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['document'], name='idx_cc_doc'),
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['symbol_name'], name='idx_cc_symbol'),
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['language', 'symbol_type'], name='idx_cc_lang_type'),
        ),
        migrations.AddIndex(
            model_name='imageresource',
            index=models.Index(fields=['document'], name='idx_img_doc'),
        ),
        migrations.AddIndex(
            model_name='imageresource',
            index=models.Index(fields=['storage_mode'], name='idx_img_mode'),
        ),
        migrations.AddConstraint(
            model_name='imageresource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('storage_mode', 'base64'), models.Q(('base64_data', ''), _negated=True)), models.Q(('storage_mode', 'oss'), models.Q(('oss_url', ''), _negated=True)), _connector='OR'), name='ck_image_storage_consistency'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['parent'], name='idx_kn_parent'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['root_type'], name='idx_kn_root_type'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['path'], name='idx_kn_path'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['dept_id'], name='idx_doc_dept'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['team_id'], name='idx_doc_team'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['node'], name='idx_doc_node'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner'], name='idx_doc_owner'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['audit_status'], name='idx_doc_audit_status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='idx_doc_status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['visibility_level', 'root_type'], name='idx_doc_visroot'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='idx_doc_hash'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['node', 'file_name', 'version_tag'], name='idx_doc_node_name_version'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('node', 'file_name', 'version_tag'), name='unique_doc_node_name_version'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('team_id__isnull', False), ('dept_id__isnull', False), _connector='OR'), name='doc_owner_scope_required'),
        ),
        migrations.AddIndex(
            model_name='docoperationlog',
            index=models.Index(fields=['action', 'created_at'], name='knowledge_d_action_f8695d_idx'),
        ),
        migrations.AddIndex(
            model_name='docoperationlog',
            index=models.Index(fields=['document', '-created_at'], name='knowledge_d_documen_09416c_idx'),
        ),
        migrations.AddIndex(
            model_name='docoperationlog',
            index=models.Index(fields=['node', '-created_at'], name='knowledge_d_node_id_3b5c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='docoperationlog',
            index=models.Index(fields=['operator', '-created_at'], name='knowledge_d_operato_0ea74d_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceblocklist',
            index=models.Index(fields=['resource_type', 'resource_id', 'blocked_user', 'status'], name='idx_block_check'),
        ),
        migrations.AddIndex(
            model_name='resourceblocklist',
            index=models.Index(fields=['blocked_user', 'status', 'resource_type', 'resource_id'], name='idx_block_user'),
        ),
        migrations.AddConstraint(
            model_name='resourceblocklist',
            constraint=models.UniqueConstraint(fields=('resource_type', 'resource_id', 'blocked_user'), name='unique_resource_block'),
        ),
        migrations.AddIndex(
            model_name='resourceshare',
            index=models.Index(fields=['resource_type', 'resource_id', 'share_scope_type', 'share_scope_id', 'status'], name='idx_share_resource_lookup'),
        ),
        migrations.AddIndex(
            model_name='resourceshare',
            index=models.Index(fields=['share_scope_type', 'share_scope_id', 'status', 'resource_type', 'resource_id'], name='idx_share_user_lookup'),
        ),
        migrations.AddConstraint(
            model_name='resourceshare',
            constraint=models.UniqueConstraint(fields=('resource_type', 'resource_id', 'share_scope_type', 'share_scope_id'), name='unique_resource_share'),
        ),
    ]
