# Generated by Django 5.2 on 2026-07-25 08:40

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kb_node_id', models.BigIntegerField(blank=True, help_text='一级知识库节点ID', null=True)),
                ('dept_node_id', models.BigIntegerField(blank=True, help_text='二级部门节点ID（归属，不可变）', null=True)),
                ('team_node_id', models.BigIntegerField(blank=True, help_text='三级团队节点ID（归属，不可变）', null=True)),
                ('category_node_id', models.BigIntegerField(blank=True, help_text='四级业务分类节点ID', null=True)),
                ('title', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=256)),
                ('file_type', models.CharField(choices=[('pdf', 'pdf'), ('docx', 'docx'), ('markdown', 'markdown'), ('txt', 'txt'), ('code', 'code'), ('config', 'config'), ('other', 'other')], max_length=16)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(help_text='sha256 文件内容哈希，防重复上传', max_length=64, unique=True)),
                ('file_path', models.CharField(blank=True, default='', help_text='本地存储路径或 OSS URL', max_length=512)),
                ('mime_type', models.CharField(blank=True, default='', max_length=64)),
                ('owner_team_id', models.BigIntegerField(blank=True, help_text='上传者所在团队快照，防止团队变动导致权限漂移', null=True)),
                ('visible_scope', models.CharField(choices=[('team', '仅归属团队'), ('dept', '归属全部门'), ('public', '全公司公开')], default='team', max_length=16)),
                ('secret_level', models.SmallIntegerField(choices=[(1, '普通'), (2, '内部'), (3, '机密'), (4, '绝密')], default=1, help_text='密级 1普通~4绝密，4禁止public')),
                ('audit_status', models.CharField(choices=[('pending_team', '待团队组长一审'), ('pending_compliance', '待合规二审'), ('rejected', '审核驳回'), ('passed', '双审通过'), ('archived', '归档'), ('deleted', '逻辑删除')], default='pending_team', max_length=32)),
                ('has_deny_user', models.BooleanField(default=False, help_text='是否有黑名单用户（加速检索跳过黑名单查询）')),
                ('has_cross_team', models.BooleanField(default=False, help_text='是否有跨团队授权（加速检索跳过跨团队查询）')),
                ('has_allow_user', models.BooleanField(default=False, help_text='是否有个人白名单（加速检索跳过白名单查询）')),
                ('allow_download', models.BooleanField(default=False, help_text='是否允许下载该文档')),
                ('allow_share', models.BooleanField(default=False, help_text='是否允许分享该文档')),
                ('root_type', models.CharField(help_text='冗余：根节点类型，加速检索过滤', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('parsing', 'parsing'), ('desensitizing', 'desensitizing'), ('chunking', 'chunking'), ('embedding', 'embedding'), ('embedding_failed', 'embedding_failed'), ('done', 'done'), ('failed', 'failed')], default='pending', help_text='处理状态: pending/parsing/.../done/failed', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('chunk_count', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_time', models.DateTimeField(blank=True, help_text='逻辑删除时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restored_at', models.DateTimeField(blank=True, help_text='恢复时间（用于审计追溯）', null=True)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, db_column='restored_by', help_text='恢复人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(help_text='文档内切片序号，从 0 开始')),
                ('chunk_type', models.CharField(choices=[('text', 'text'), ('table', 'table'), ('image', 'image'), ('code', 'code'), ('config', 'config')], default='text', max_length=16)),
                ('content', models.TextField(help_text='切片原文')),
                ('content_length', models.IntegerField(default=0)),
                ('section_path', models.CharField(blank=True, default='', help_text='如 "第一章>1.1 节>表 1-2"', max_length=512)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('image_id', models.BigIntegerField(blank=True, help_text='若 chunk_type=image，关联 image_resource.id', null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'db_table': 'knowledge_document_chunk',
            },
        ),
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(default='python', max_length=32)),
                ('symbol_type', models.CharField(choices=[('function', 'function'), ('class', 'class'), ('method', 'method'), ('module', 'module'), ('variable', 'variable')], max_length=16)),
                ('symbol_name', models.CharField(max_length=128)),
                ('signature', models.TextField(blank=True, default='', help_text='函数签名，如 def foo(a:int)->str')),
                ('params', models.JSONField(blank=True, default=list, help_text='参数列表 [{name,type,default}]')),
                ('docstring', models.TextField(blank=True, default='')),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('parent_symbol', models.CharField(blank=True, default='', help_text='所属类名，用于方法', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='code_chunks', to='knowledge.document')),
                ('chunk', models.ForeignKey(db_column='chunk_id', on_delete=django.db.models.deletion.CASCADE, related_name='code_meta', to='knowledge.documentchunk')),
            ],
            options={
                'db_table': 'knowledge_code_chunk',
            },
        ),
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('storage_mode', models.CharField(choices=[('base64', 'base64'), ('oss', 'oss')], default='base64', max_length=8)),
                ('base64_data', models.TextField(blank=True, default='', help_text='当 storage_mode=base64 时存储')),
                ('oss_url', models.CharField(blank=True, default='', help_text='当 storage_mode=oss 时存储', max_length=512)),
                ('mime_type', models.CharField(default='image/png', max_length=32)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('size_bytes', models.IntegerField(default=0)),
                ('ocr_text', models.TextField(blank=True, default='', help_text='OCR 结果，便于图片检索')),
                ('caption', models.TextField(blank=True, default='', help_text='图片说明/图注')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='knowledge.document')),
            ],
            options={
                'db_table': 'knowledge_image',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('root_type', models.CharField(max_length=32)),
                ('node_type', models.CharField(choices=[('root', 'root'), ('folder', 'folder'), ('leaf', 'leaf')], default='folder', max_length=16)),
                ('node_level', models.SmallIntegerField(default=4, help_text='节点层级: 1=kb 2=dept 3=team 4+=业务分类（≥4 支持无限子级，仅团队组长可管理）')),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(default='/', help_text='冗余路径 /kb_id/dept_id/team_id/cat_id/...（支持无限级业务分类）', max_length=512)),
                ('depth', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('order_no', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ref_id', models.BigIntegerField(blank=True, help_text='关联源对象 ID：node_level=2 存 dept.id，node_level=3 存 team.id', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_node',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='node',
            field=models.ForeignKey(db_column='node_id', help_text='关联节点（category_node）', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='knowledge.knowledgenode'),
        ),
        migrations.CreateModel(
            name='DocOperationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('doc_create', '上传文档'), ('doc_delete', '删除文档'), ('doc_visibility_change', '修改可见范围'), ('doc_download', '下载文档'), ('doc_reparse', '重新解析'), ('doc_restore', '恢复文档'), ('node_create', '创建节点'), ('node_update', '修改节点'), ('node_delete', '删除节点'), ('doc_audit_team_pass', '团队一审通过'), ('doc_audit_team_reject', '团队一审驳回'), ('doc_audit_compliance_pass', '合规二审通过'), ('doc_audit_compliance_reject', '合规二审驳回'), ('doc_grant', '授权（白名单/跨团队）'), ('doc_revoke', '撤销授权'), ('doc_grant_expire', '授权到期'), ('doc_deny_add', '添加黑名单'), ('doc_deny_remove', '移除黑名单'), ('doc_archive', '归档文档'), ('doc_physical_destroy', '物理销毁')], db_index=True, max_length=32)),
                ('operator_name', models.CharField(blank=True, default='', max_length=128)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='操作详情，如变更前后的值、目标用户等')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator', models.ForeignKey(blank=True, db_column='operator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.document')),
                ('node', models.ForeignKey(blank=True, db_column='node_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_doc_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodePermissionOverride',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('user', 'user'), ('team', 'team'), ('role', 'role')], max_length=16)),
                ('subject_id', models.BigIntegerField()),
                ('action', models.CharField(choices=[('read', 'read'), ('write', 'write'), ('admin', 'admin')], default='read', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='knowledge.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_node_permission',
            },
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document'], name='idx_chunk_doc'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_type'], name='idx_chunk_type'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['document'], name='idx_cc_doc'),
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['symbol_name'], name='idx_cc_symbol'),
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['language', 'symbol_type'], name='idx_cc_lang_type'),
        ),
        migrations.AddIndex(
            model_name='imageresource',
            index=models.Index(fields=['document'], name='idx_img_doc'),
        ),
        migrations.AddIndex(
            model_name='imageresource',
            index=models.Index(fields=['storage_mode'], name='idx_img_mode'),
        ),
        migrations.AddConstraint(
            model_name='imageresource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('storage_mode', 'base64'), models.Q(('base64_data', ''), _negated=True)), models.Q(('storage_mode', 'oss'), models.Q(('oss_url', ''), _negated=True)), _connector='OR'), name='ck_image_storage_consistency'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['parent'], name='idx_kn_parent'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['root_type'], name='idx_kn_root_type'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['path'], name='idx_kn_path'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['kb_node_id'], name='idx_doc_kb_node'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['dept_node_id'], name='idx_doc_dept_node'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['team_node_id'], name='idx_doc_team_node'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['node'], name='idx_doc_node'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner'], name='idx_doc_owner'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['audit_status'], name='idx_doc_audit_status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='idx_doc_status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['visible_scope', 'root_type'], name='idx_doc_visroot'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='idx_doc_hash'),
        ),
        migrations.AddIndex(
            model_name='docoperationlog',
            index=models.Index(fields=['action', 'created_at'], name='knowledge_d_action_f8695d_idx'),
        ),
        migrations.AddIndex(
            model_name='docoperationlog',
            index=models.Index(fields=['document', '-created_at'], name='knowledge_d_documen_09416c_idx'),
        ),
        migrations.AddIndex(
            model_name='docoperationlog',
            index=models.Index(fields=['node', '-created_at'], name='knowledge_d_node_id_3b5c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='docoperationlog',
            index=models.Index(fields=['operator', '-created_at'], name='knowledge_d_operato_0ea74d_idx'),
        ),
        migrations.AddIndex(
            model_name='nodepermissionoverride',
            index=models.Index(fields=['subject_type', 'subject_id'], name='idx_npo_subject'),
        ),
        migrations.AlterUniqueTogether(
            name='nodepermissionoverride',
            unique_together={('node', 'subject_type', 'subject_id', 'action')},
        ),
    ]
