# Generated by Django 5.2 on 2026-07-15 12:34

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=256)),
                ('file_type', models.CharField(choices=[('pdf', 'pdf'), ('docx', 'docx'), ('markdown', 'markdown'), ('txt', 'txt'), ('code', 'code'), ('config', 'config'), ('other', 'other')], max_length=16)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(help_text='sha256 文件内容哈希，防重复上传', max_length=64, unique=True)),
                ('file_path', models.CharField(blank=True, default='', help_text='本地存储路径或 OSS URL', max_length=512)),
                ('mime_type', models.CharField(blank=True, default='', max_length=64)),
                ('owner_team_id', models.BigIntegerField(blank=True, help_text='上传者所在团队快照，防止团队变动导致权限漂移', null=True)),
                ('visibility', models.SmallIntegerField(choices=[(1, '私有'), (2, '团队'), (3, '公开'), (4, '系统级')], default=1)),
                ('root_type', models.CharField(help_text='冗余：根节点类型，加速检索过滤', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('parsing', 'parsing'), ('desensitizing', 'desensitizing'), ('chunking', 'chunking'), ('embedding', 'embedding'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('chunk_count', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(help_text='文档内切片序号，从 0 开始')),
                ('chunk_type', models.CharField(choices=[('text', 'text'), ('table', 'table'), ('image', 'image'), ('code', 'code'), ('config', 'config')], default='text', max_length=16)),
                ('content', models.TextField(help_text='切片原文')),
                ('content_length', models.IntegerField(default=0)),
                ('section_path', models.CharField(blank=True, default='', help_text='如 "第一章>1.1 节>表 1-2"', max_length=512)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('image_id', models.BigIntegerField(blank=True, help_text='若 chunk_type=image，关联 image_resource.id', null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'db_table': 'document_chunk',
            },
        ),
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(default='python', max_length=32)),
                ('symbol_type', models.CharField(choices=[('function', 'function'), ('class', 'class'), ('method', 'method'), ('module', 'module'), ('variable', 'variable')], max_length=16)),
                ('symbol_name', models.CharField(max_length=128)),
                ('signature', models.TextField(blank=True, default='', help_text='函数签名，如 def foo(a:int)->str')),
                ('params', models.JSONField(blank=True, default=list, help_text='参数列表 [{name,type,default}]')),
                ('docstring', models.TextField(blank=True, default='')),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('parent_symbol', models.CharField(blank=True, default='', help_text='所属类名，用于方法', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='code_chunks', to='knowledge.document')),
                ('chunk', models.ForeignKey(db_column='chunk_id', on_delete=django.db.models.deletion.CASCADE, related_name='code_meta', to='knowledge.documentchunk')),
            ],
            options={
                'db_table': 'code_chunk',
            },
        ),
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('storage_mode', models.CharField(choices=[('base64', 'base64'), ('oss', 'oss')], default='base64', max_length=8)),
                ('base64_data', models.TextField(blank=True, default='', help_text='当 storage_mode=base64 时存储')),
                ('oss_url', models.CharField(blank=True, default='', help_text='当 storage_mode=oss 时存储', max_length=512)),
                ('mime_type', models.CharField(default='image/png', max_length=32)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('size_bytes', models.IntegerField(default=0)),
                ('ocr_text', models.TextField(blank=True, default='', help_text='OCR 结果，便于图片检索')),
                ('caption', models.TextField(blank=True, default='', help_text='图片说明/图注')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='knowledge.document')),
            ],
            options={
                'db_table': 'image_resource',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('root_type', models.CharField(choices=[('company_doc', '企业文档'), ('code_kb', '代码知识库'), ('general_reasoning', '通用推理'), ('ops_fault', '运维故障')], max_length=32)),
                ('node_type', models.CharField(choices=[('root', 'root'), ('folder', 'folder'), ('leaf', 'leaf')], default='folder', max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(default='/', max_length=512)),
                ('depth', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('order_no', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_node',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='node',
            field=models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='knowledge.knowledgenode'),
        ),
        migrations.CreateModel(
            name='NodePermissionOverride',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('user', 'user'), ('team', 'team'), ('role', 'role')], max_length=16)),
                ('subject_id', models.BigIntegerField()),
                ('action', models.CharField(choices=[('read', 'read'), ('write', 'write'), ('admin', 'admin')], default='read', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='knowledge.knowledgenode')),
            ],
            options={
                'db_table': 'node_permission_override',
            },
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document'], name='idx_chunk_doc'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_type'], name='idx_chunk_type'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['document'], name='idx_cc_doc'),
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['symbol_name'], name='idx_cc_symbol'),
        ),
        migrations.AddIndex(
            model_name='codechunk',
            index=models.Index(fields=['language', 'symbol_type'], name='idx_cc_lang_type'),
        ),
        migrations.AddIndex(
            model_name='imageresource',
            index=models.Index(fields=['document'], name='idx_img_doc'),
        ),
        migrations.AddIndex(
            model_name='imageresource',
            index=models.Index(fields=['storage_mode'], name='idx_img_mode'),
        ),
        migrations.AddConstraint(
            model_name='imageresource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('storage_mode', 'base64'), models.Q(('base64_data', ''), _negated=True)), models.Q(('storage_mode', 'oss'), models.Q(('oss_url', ''), _negated=True)), _connector='OR'), name='ck_image_storage_consistency'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['parent'], name='idx_kn_parent'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['root_type'], name='idx_kn_root_type'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['path'], name='idx_kn_path'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['node'], name='idx_doc_node'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner'], name='idx_doc_owner'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='idx_doc_status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['visibility', 'root_type'], name='idx_doc_visroot'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='idx_doc_hash'),
        ),
        migrations.AddIndex(
            model_name='nodepermissionoverride',
            index=models.Index(fields=['subject_type', 'subject_id'], name='idx_npo_subject'),
        ),
        migrations.AlterUniqueTogether(
            name='nodepermissionoverride',
            unique_together={('node', 'subject_type', 'subject_id', 'action')},
        ),
    ]
