# Generated by Django 5.2 on 2026-08-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenode',
            name='node_kind',
            field=models.CharField(choices=[('ROOT', '根节点'), ('ORG', '组织节点'), ('FOLDER', '文件夹')], default='FOLDER', help_text='节点性质: ROOT=根节点 / ORG=组织节点(部门/团队,由组织同步创建) / FOLDER=文件夹(手动创建,文档只能挂在文件夹下)', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='visibility_level',
            field=models.CharField(blank=True, choices=[('TEAM_ONLY', '仅团队'), ('DEPT_ONLY', '仅部门'), ('PUBLIC', '全局公开')], help_text='节点可见范围: TEAM_ONLY/DEPT_ONLY/PUBLIC，NULL=继承父级（root 兜底 PUBLIC）', max_length=32, null=True),
        ),
    ]
