# Generated by Django 5.2 on 2026-07-26 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version_tag',
            field=models.CharField(blank=True, default='', help_text='版本标签，如 v1.0、v2.1，用于区分同一文件的不同版本', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_hash',
            field=models.CharField(help_text='sha256 文件内容哈希，用于版本识别', max_length=64),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['node', 'file_name', 'version_tag'], name='idx_doc_node_name_version'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('node', 'file_name', 'version_tag'), name='unique_doc_node_name_version'),
        ),
    ]
