# Generated by Django 5.2 on 2026-07-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='codechunk',
            table='knowledge_code_chunk',
        ),
        migrations.AlterModelTable(
            name='document',
            table='knowledge_document',
        ),
        migrations.AlterModelTable(
            name='documentchunk',
            table='knowledge_document_chunk',
        ),
        migrations.AlterModelTable(
            name='imageresource',
            table='knowledge_image_resource',
        ),
        migrations.AlterModelTable(
            name='nodepermissionoverride',
            table='knowledge_node_permission_override',
        ),
    ]
