# Generated by Django 5.2 on 2026-07-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_codechunk_table_alter_document_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('parsing', 'parsing'), ('desensitizing', 'desensitizing'), ('chunking', 'chunking'), ('embedding', 'embedding'), ('embedding_failed', 'embedding_failed'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=16),
        ),
    ]
