# Generated by Django 5.2 on 2026-08-07 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgenode_node_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='doc_owner_scope_required',
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('visibility_level', 'PUBLIC'), ('team_id__isnull', False), ('dept_id__isnull', False), _connector='OR'), name='doc_owner_scope_required'),
        ),
    ]
