# Generated by Django 5.2 on 2026-07-23 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_document_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='restored_at',
            field=models.DateTimeField(blank=True, help_text='恢复时间（用于审计追溯）', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='restored_by',
            field=models.ForeignKey(blank=True, db_column='restored_by', help_text='恢复人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
