# Generated by Django 5.2 on 2026-08-09 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_remove_document_doc_owner_scope_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_doc_node_name_version',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='idx_doc_node_name_version',
        ),
        migrations.AddField(
            model_name='document',
            name='content_sample',
            field=models.TextField(blank=True, default='', help_text='文本内容样本（空白归一化后截断），用于版本相似度判定'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否活跃版本（检索/列表默认只召回活跃版本）'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['node', 'file_name', 'dept_id', 'team_id', 'version_tag'], name='idx_doc_node_name_version'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('node', 'file_name', 'dept_id', 'team_id', 'version_tag'), name='unique_doc_node_name_version'),
        ),
    ]
