# Generated by Django 5.2 on 2026-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_remove_document_unique_doc_node_name_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='graph_status',
            field=models.CharField(choices=[('pending', 'pending'), ('extracting', 'extracting'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', help_text='图谱构建状态: pending/extracting/done/failed/skipped', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='wiki_status',
            field=models.CharField(choices=[('pending', 'pending'), ('extracting', 'extracting'), ('done', 'done'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', help_text='Wiki 构建状态: pending/extracting/done/failed/skipped', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='graph_pending',
            field=models.BooleanField(default=False, help_text='图谱待构建标记（防抖合并派发）'),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='wiki_pending',
            field=models.BooleanField(default=False, help_text='Wiki 待构建标记（防抖合并派发）'),
        ),
    ]
