# Generated by Django 5.2 on 2026-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_document_restored_at_document_restored_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgenode',
            name='root_type',
            field=models.CharField(max_length=32),
        ),
    ]
