# Generated by Django 5.2 on 2026-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_knowledgenode_root_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, '私有'), (2, '部门'), (3, '团队'), (4, '公开')], default=1),
        ),
    ]
