# Generated by Django 5.2 on 2026-08-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_document_graph_status_document_wiki_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'pdf'), ('docx', 'docx'), ('markdown', 'markdown'), ('txt', 'txt'), ('code', 'code'), ('config', 'config'), ('image', 'image'), ('other', 'other')], max_length=16),
        ),
    ]
