# Generated by Django 5.2 on 2026-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_alter_document_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrUsageCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, help_text='固定为 1（单行计数器）', primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0, help_text='已累计的 OCR 调用次数')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最近一次计数更新时间')),
            ],
            options={
                'verbose_name': 'OCR 调用计数（开发期）',
                'verbose_name_plural': 'OCR 调用计数（开发期）',
                'db_table': 'knowledge_ocr_usage_counter',
            },
        ),
    ]
