# Generated by Django 5.2 on 2026-08-04 18:11

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0001_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('summary', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='', help_text='Wiki 正文，Markdown 格式')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('expired', '已过期')], default='draft', max_length=16)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='页面语义向量（BGE-M3 1024 维）', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, db_column='community_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.graphcommunity')),
                ('node', models.ForeignKey(blank=True, db_column='node_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.knowledgenode')),
            ],
            options={
                'db_table': 'wiki_page',
            },
        ),
        migrations.CreateModel(
            name='WikiLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_text', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_page', models.ForeignKey(db_column='source_page_id', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='wiki.wikipage')),
                ('target_page', models.ForeignKey(db_column='target_page_id', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='wiki.wikipage')),
            ],
            options={
                'db_table': 'wiki_link',
            },
        ),
        migrations.CreateModel(
            name='WikiSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='wiki.wikipage')),
            ],
            options={
                'db_table': 'wiki_section',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_wp_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['status'], name='wiki_page_status_167f10_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['node'], name='wiki_page_node_id_9328a1_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['community'], name='wiki_page_communi_959f0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wikilink',
            unique_together={('source_page', 'target_page')},
        ),
        migrations.AddIndex(
            model_name='wikisection',
            index=models.Index(fields=['page'], name='wiki_sectio_page_id_d569fd_idx'),
        ),
    ]
