# Generated by Django 5.2 on 2026-08-16 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='expire_reason',
            field=models.TextField(blank=True, default='', help_text='标记过期时填写的原因'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='expired_at',
            field=models.DateTimeField(blank=True, help_text='标记过期时间', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='expired_by',
            field=models.ForeignKey(blank=True, db_column='expired_by_id', help_text='标记过期的操作人（文档变化自动过期时为空）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
