# Generated by Django 5.2 on 2026-08-01 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('real_name', models.CharField(default='', max_length=64)),
                ('avatar_url', models.CharField(blank=True, max_length=512, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('active', '正常'), ('disabled', '已禁用'), ('locked', '已锁定')], default='active', max_length=16)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(help_text='全局唯一，如 super_admin / team_leader', max_length=64, unique=True, verbose_name='角色标识')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, null=True)),
                ('role_type', models.CharField(choices=[('GLOBAL', '全局角色（授权无需绑定 Scope）'), ('DEPT_SCOPE', '部门管理角色（授权必须绑定具体 Dept）'), ('TEAM_SCOPE', '团队管理角色（授权必须绑定具体 Team）'), ('NORMAL_USER', '普通角色（随人事归属生效）')], default='NORMAL_USER', help_text='决定授权时是否需要绑定管辖 Scope', max_length=32, verbose_name='角色类型')),
                ('data_scope', models.CharField(choices=[('TEAM', '团队级'), ('DEPT', '部门级'), ('GLOBAL', '全局级')], default='TEAM', help_text='角色默认数据范围', max_length=16, verbose_name='数据范围等级')),
                ('is_builtin', models.BooleanField(default=False, help_text='内置角色不可删除')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '角色',
                'db_table': 'user_role_list',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='部门名称')),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='部门编码')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='父部门，树形结构', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.department')),
            ],
            options={
                'verbose_name': '部门',
                'db_table': 'user_department',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='主部门', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.department'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(help_text='三段式 module.resource.action', max_length=128, unique=True, verbose_name='权限点标识')),
                ('permission_name', models.CharField(max_length=64, verbose_name='显示名称')),
                ('module', models.CharField(help_text='org / user / kb / system / compliance / audit', max_length=32, verbose_name='模块')),
                ('is_builtin', models.BooleanField(default=False, help_text='内置权限点不可删除', verbose_name='是否内置')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '权限点',
                'db_table': 'user_permission_list',
                'indexes': [models.Index(fields=['module'], name='user_permis_module_45e522_idx'), models.Index(fields=['permission_key'], name='user_permis_permiss_6c1db2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text='操作类别枚举', max_length=32)),
                ('target_type', models.CharField(choices=[('USER', '用户'), ('ROLE', '角色'), ('DEPT', '部门'), ('TEAM', '团队'), ('KNOWLEDGE_BASE', '知识库'), ('KNOWLEDGE_NODE', '知识节点'), ('DOCUMENT', '文档'), ('TICKET', '工单'), ('LOGIN', '登录')], help_text='操作对象类型', max_length=32)),
                ('target_id', models.BigIntegerField(blank=True, help_text='对象 ID', null=True)),
                ('scope_type', models.CharField(blank=True, choices=[('GLOBAL', '全局'), ('DEPT', '部门'), ('TEAM', '团队'), ('NONE', '无（全局角色）')], default='NONE', max_length=16)),
                ('scope_id', models.BigIntegerField(blank=True, null=True)),
                ('before_snapshot', models.JSONField(blank=True, help_text='变更前快照（无则 null）', null=True)),
                ('after_snapshot', models.JSONField(blank=True, help_text='变更后快照（无则 null）', null=True)),
                ('result', models.CharField(default='SUCCESS', help_text='SUCCESS / FAIL + 失败码', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='事件时间，按此字段冷热归档')),
                ('actor', models.ForeignKey(blank=True, help_text='操作人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='若对象是人，便于检索', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, help_text='涉及角色（有则填）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.role')),
            ],
            options={
                'verbose_name': '权限审计日志',
                'db_table': 'permission_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionApprovalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=64, unique=True, verbose_name='工单号')),
                ('change_type', models.CharField(choices=[('GRANT', '授权'), ('REVOKE', '撤销'), ('SCOPE_CHANGE', '范围变更'), ('EXPIRE_EXTEND', '延期')], help_text='GRANT/REVOKE/SCOPE_CHANGE/EXPIRE_EXTEND', max_length=16)),
                ('scope_type', models.CharField(choices=[('GLOBAL', '全局'), ('DEPT', '部门'), ('TEAM', '团队'), ('NONE', '无（全局角色）')], default='NONE', help_text='GLOBAL/DEPT/TEAM/NONE', max_length=16)),
                ('scope_id', models.BigIntegerField(blank=True, help_text='dept_id 或 team_id（scope_type 对应）', null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='申请理由')),
                ('approval_chain', models.JSONField(blank=True, default=list, help_text='审批链快照，顺序执行')),
                ('current_step', models.IntegerField(default=0, help_text='当前审批节点索引')),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('CANCELLED', '已撤回'), ('EXECUTED', '已执行')], default='PENDING', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, help_text='最终通过时间', null=True)),
                ('executed_at', models.DateTimeField(blank=True, help_text='审批通过后真正写入授权表的时间（异步 worker 执行）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(help_text='发起人', on_delete=django.db.models.deletion.CASCADE, related_name='applied_tickets', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='被授权/被撤销对象', on_delete=django.db.models.deletion.CASCADE, related_name='targeted_tickets', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, help_text='涉及角色', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='users.role')),
            ],
            options={
                'verbose_name': '权限审批工单',
                'db_table': 'permission_approval_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.permission')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role')),
            ],
            options={
                'db_table': 'user_role_permission_rel',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='团队名称')),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='团队编码')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='所属部门，强制绑定', on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='users.department')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '团队',
                'db_table': 'user_team',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, help_text='所属团队（单团队）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.team'),
        ),
        migrations.CreateModel(
            name='UserDeptScopeRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('ACTIVE', '生效中'), ('EXPIRED', '已过期'), ('REVOKED', '已撤销')], default='PENDING', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_rels', to='users.department')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_scope_rels', to='users.role')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_scope_rels', to='users.permissionapprovalticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_scope_rels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_role_dept_scope_rel',
            },
        ),
        migrations.CreateModel(
            name='UserRoleRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('effective_from', models.DateTimeField(blank=True, help_text='NULL = 立即生效', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL = 永久有效', null=True)),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('ACTIVE', '生效中'), ('EXPIRED', '已过期'), ('REVOKED', '已撤销')], default='PENDING', help_text='PENDING=待审批 ACTIVE=生效 EXPIRED=过期 REVOKED=撤销', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_rels', to='users.role')),
                ('ticket', models.ForeignKey(blank=True, help_text='关联审批工单（有则填）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role_rels', to='users.permissionapprovalticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_rels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_role_global_rel',
            },
        ),
        migrations.CreateModel(
            name='UserTeamScopeRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('ACTIVE', '生效中'), ('EXPIRED', '已过期'), ('REVOKED', '已撤销')], default='PENDING', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_scope_rels', to='users.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_rels', to='users.team')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_scope_rels', to='users.permissionapprovalticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_scope_rels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_role_team_scope_rel',
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='user_depart_parent__42c19c_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_dept_name_active'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['action', 'created_at'], name='permission__action_6e9669_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='permission__actor_i_da98be_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='permission__target__4176e0_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['target_user', '-created_at'], name='permission__target__1492c7_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionapprovalticket',
            index=models.Index(fields=['status'], name='permission__status_5f9b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionapprovalticket',
            index=models.Index(fields=['applicant'], name='permission__applica_af0b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionapprovalticket',
            index=models.Index(fields=['target_user'], name='permission__target__02a2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionapprovalticket',
            index=models.Index(fields=['change_type', 'status'], name='permission__change__d44f6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermissionrel',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['department'], name='user_team_departm_b3125c_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'department_id'), name='unique_team_name_per_dept_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department'], name='user_accoun_departm_3ccda3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['team'], name='user_accoun_team_id_a86cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='user_accoun_status_3c356a_idx'),
        ),
        migrations.AddIndex(
            model_name='userdeptscoperel',
            index=models.Index(fields=['user', 'status'], name='user_role_d_user_id_0c8bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='userdeptscoperel',
            index=models.Index(fields=['dept', 'status'], name='user_role_d_dept_id_7ccbf6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdeptscoperel',
            unique_together={('user', 'role', 'dept')},
        ),
        migrations.AddIndex(
            model_name='userrolerel',
            index=models.Index(fields=['user', 'status'], name='user_role_g_user_id_fc0c39_idx'),
        ),
        migrations.AddIndex(
            model_name='userrolerel',
            index=models.Index(fields=['role', 'status'], name='user_role_g_role_id_8b2107_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrolerel',
            unique_together={('user', 'role')},
        ),
        migrations.AddIndex(
            model_name='userteamscoperel',
            index=models.Index(fields=['user', 'status'], name='user_role_t_user_id_f9cf49_idx'),
        ),
        migrations.AddIndex(
            model_name='userteamscoperel',
            index=models.Index(fields=['team', 'status'], name='user_role_t_team_id_f01a9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userteamscoperel',
            unique_together={('user', 'role', 'team')},
        ),
    ]
