# Generated by Django 5.2 on 2026-07-25 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('real_name', models.CharField(default='', max_length=64)),
                ('avatar_url', models.CharField(blank=True, max_length=512, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('active', '正常'), ('disabled', '已禁用'), ('locked', '已锁定')], default='active', max_length=16)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_role_list',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.department')),
            ],
            options={
                'db_table': 'user_department',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.department'),
        ),
        migrations.CreateModel(
            name='DocAllowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.BigIntegerField()),
                ('uid', models.BigIntegerField()),
                ('expire_time', models.DateTimeField(blank=True, help_text='过期时间，NULL 表示永久', null=True)),
                ('audit_record_id', models.BigIntegerField(blank=True, help_text='关联审批工单 ID', null=True)),
                ('create_by', models.BigIntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doc_allow_user',
                'indexes': [models.Index(fields=['doc_id'], name='doc_allow_u_doc_id_de0b59_idx'), models.Index(fields=['uid'], name='doc_allow_u_uid_775ad8_idx')],
                'unique_together': {('doc_id', 'uid')},
            },
        ),
        migrations.CreateModel(
            name='DocCrossTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.BigIntegerField()),
                ('team_code', models.CharField(max_length=64)),
                ('expire_time', models.DateTimeField(blank=True, help_text='过期时间，NULL 表示永久', null=True)),
                ('audit_record_id', models.BigIntegerField(blank=True, help_text='关联审批工单 ID', null=True)),
                ('create_by', models.BigIntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doc_cross_team',
                'indexes': [models.Index(fields=['doc_id'], name='doc_cross_t_doc_id_192706_idx'), models.Index(fields=['team_code'], name='doc_cross_t_team_co_12bc54_idx')],
                'unique_together': {('doc_id', 'team_code')},
            },
        ),
        migrations.CreateModel(
            name='DocDenyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.BigIntegerField()),
                ('uid', models.BigIntegerField()),
                ('create_by', models.BigIntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doc_deny_user',
                'indexes': [models.Index(fields=['doc_id'], name='doc_deny_us_doc_id_ebd001_idx'), models.Index(fields=['uid'], name='doc_deny_us_uid_eaad32_idx')],
                'unique_together': {('doc_id', 'uid')},
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('module', models.CharField(help_text='knowledge / user / audit / system', max_length=32)),
                ('action', models.CharField(default='read', help_text='read / upload / edit / delete / export / share / manage / restore / config', max_length=16)),
                ('scope', models.CharField(default='team', help_text='all / department / team', max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_permission_list',
                'indexes': [models.Index(fields=['module'], name='user_permis_module_45e522_idx'), models.Index(fields=['action'], name='user_permis_action_9c3916_idx'), models.Index(fields=['scope'], name='user_permis_scope_1a1566_idx'), models.Index(fields=['module', 'action', 'scope'], name='user_permis_module_724d29_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role')),
            ],
            options={
                'db_table': 'user_role_permission_rel',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_team',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account_role_rel',
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_team', models.CharField(default='member', max_length=32)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to='users.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account_team_rel',
            },
        ),
        migrations.CreateModel(
            name='AccessApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('doc', '文档'), ('team', '团队'), ('dept', '部门'), ('all', '全平台')], default='doc', max_length=16)),
                ('target_id', models.BigIntegerField(blank=True, help_text='doc_id / team_id / dept_id', null=True)),
                ('action', models.CharField(choices=[('read', '只读'), ('download', '下载')], default='read', max_length=16)),
                ('reason', models.TextField(blank=True, default='', help_text='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=16)),
                ('reviewer_comment', models.TextField(blank=True, default='', help_text='审批意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['applicant'], name='access_appl_applica_58111a_idx'), models.Index(fields=['status'], name='access_appl_status_ea0fa1_idx'), models.Index(fields=['target_type', 'target_id'], name='access_appl_target__262cd1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='user_depart_parent__42c19c_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_dept_name_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department'], name='user_accoun_departm_3ccda3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='user_accoun_status_3c356a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['department'], name='user_team_departm_b3125c_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'department_id'), name='unique_team_name_per_dept_active'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='user_accoun_role_id_d2f115_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
        migrations.AddIndex(
            model_name='userteam',
            index=models.Index(fields=['team'], name='user_accoun_team_id_dbbd47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userteam',
            unique_together={('user', 'team')},
        ),
    ]
