# Generated by Django 5.2 on 2026-07-26 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessapplication',
            name='first_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessapplication',
            name='first_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessapplication',
            name='need_double_approval',
            field=models.BooleanField(default=False, help_text='向上调整可见范围时需要双层审批'),
        ),
        migrations.AddField(
            model_name='accessapplication',
            name='new_visibility',
            field=models.CharField(blank=True, default='', help_text='仅 visibility_change 动作使用，新可见范围: team/dept/public', max_length=16),
        ),
        migrations.AlterField(
            model_name='accessapplication',
            name='action',
            field=models.CharField(choices=[('read', '只读'), ('download', '下载'), ('visibility_change', '修改可见范围')], default='read', max_length=32),
        ),
    ]
