# Generated by Django 5.2 on 2026-07-18 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('read', '只读'), ('edit', '编辑'), ('export', '导出')], default='read', max_length=16)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='过期时间，NULL 表示永久', null=True)),
            ],
            options={
                'db_table': 'document_permission',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(default='read', help_text='read / upload / edit / delete / export / share / manage / restore / config', max_length=16),
        ),
        migrations.AddField(
            model_name='permission',
            name='scope',
            field=models.CharField(default='personal', help_text='all / department / team / personal', max_length=16),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(help_text='knowledge / user / audit / system', max_length=32),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['action'], name='permission_action_d0629e_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['scope'], name='permission_scope_4cfd36_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module', 'action', 'scope'], name='permission_module_46ea14_idx'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='knowledge.document'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='granted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['granted_to'], name='document_pe_granted_cb1f52_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['document'], name='document_pe_documen_2115de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('document', 'granted_to', 'action')},
        ),
    ]
