# Generated by Django 5.2 on 2026-07-18 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rbac_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCrossScopeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('department', '部门'), ('team', '团队')], max_length=16)),
                ('scope_id', models.IntegerField(help_text='部门ID 或 团队ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_scope_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_cross_scope_access',
                'indexes': [models.Index(fields=['user'], name='user_cross__user_id_53fe42_idx'), models.Index(fields=['scope_type', 'scope_id'], name='user_cross__scope_t_265105_idx')],
                'unique_together': {('user', 'scope_type', 'scope_id')},
            },
        ),
    ]
