# Generated by Django 5.2 on 2026-07-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cross_scope_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercrossscopeaccess',
            name='actions',
            field=models.CharField(blank=True, default='read', help_text='逗号分隔的动作: read,upload,edit,delete,export,share', max_length=255),
        ),
    ]
