# Generated by Django 5.2 on 2026-08-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_user_unique_email_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
