# Generated by Django 5.2 on 2026-07-18 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cross_scope_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScopePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('department', '部门'), ('team', '团队')], max_length=16)),
                ('scope_id', models.IntegerField(help_text='部门ID 或 团队ID')),
                ('actions', models.CharField(blank=True, default='read', help_text='逗号分隔: read,upload,edit,delete,export,share', max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_scope_permission',
                'indexes': [models.Index(fields=['user'], name='user_scope__user_id_c6658b_idx'), models.Index(fields=['scope_type', 'scope_id'], name='user_scope__scope_t_0df408_idx')],
                'unique_together': {('user', 'scope_type', 'scope_id')},
            },
        ),
    ]
