# Generated by Django 5.2 on 2026-07-18 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userscopepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(blank=True, default='', help_text='申请的权限 code（冗余字段，便于无 permission 时使用）', max_length=64)),
                ('applied_scope', models.CharField(choices=[('team', '团队级'), ('department', '部门级'), ('all', '全平台')], default='team', help_text='申请的范围：team/department/all', max_length=16)),
                ('reason', models.TextField(blank=True, default='', help_text='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=16)),
                ('reviewer_comment', models.TextField(blank=True, default='', help_text='审批意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_applications', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, help_text='指定的审批人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(blank=True, help_text='申请的权限项，NULL 表示申请角色', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.permission')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permission_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['applicant'], name='permission__applica_928e26_idx'), models.Index(fields=['approver'], name='permission__approve_f368ac_idx'), models.Index(fields=['status'], name='permission__status_e5a69f_idx')],
            },
        ),
    ]
