# Generated by Django 5.2 on 2026-08-02 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_roleconflictrule_and_previous_role'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roleconflictrule',
            new_name='role_confli_role_a__5529e8_idx',
            old_name='role_conf_role_a_idx',
        ),
        migrations.RenameIndex(
            model_name='roleconflictrule',
            new_name='role_confli_role_b__f27cb6_idx',
            old_name='role_conf_role_b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userdeptscoperel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userteamscoperel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='permissionapprovalticket',
            name='role',
            field=models.ForeignKey(blank=True, help_text='涉及角色（GRANT 为新角色，ROLE_CHANGE 为新角色，previous_role 为旧角色）', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='users.role'),
        ),
        migrations.AddConstraint(
            model_name='userdeptscoperel',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'dept'), name='unique_user_dept_active'),
        ),
        migrations.AddConstraint(
            model_name='userteamscoperel',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'team'), name='unique_user_team_active'),
        ),
    ]
