# Generated by Django 5.2 on 2026-08-08 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_install_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_no', models.CharField(max_length=32, unique=True, verbose_name='工单号')),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='任务名')),
                ('biz_type', models.CharField(choices=[('permission', '权限审批'), ('config', '配置变更'), ('model', '模型变更'), ('schedule', '定时任务')], db_index=True, max_length=16, verbose_name='工单类型')),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('CANCELLED', '已撤回'), ('EXECUTED', '已执行')], db_index=True, default='PENDING', max_length=16, verbose_name='状态')),
                ('risk_level', models.CharField(default='normal', max_length=8, verbose_name='风险等级')),
                ('approval_chain', models.JSONField(blank=True, default=list, help_text='审批链快照，顺序执行')),
                ('current_step', models.IntegerField(default=0, help_text='当前审批节点索引')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='业务详情')),
                ('operation', models.CharField(blank=True, default='', max_length=20, verbose_name='操作类型')),
                ('config_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='配置项')),
                ('target_model_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='目标模型ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('applicant', models.ForeignKey(blank=True, help_text='发起人（权限工单=提单人；配置/模型工单=创建人）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_tickets_applied', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '统一工单',
                'verbose_name_plural': '统一工单',
                'db_table': 'unified_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketFlowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='流转动作', max_length=16)),
                ('step', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, default='', help_text='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='操作人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='flow_logs', to='users.unifiedticket')),
            ],
            options={
                'verbose_name': '工单流转日志',
                'db_table': 'ticket_flow_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionTicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('GRANT', '授权'), ('REVOKE', '撤销'), ('SCOPE_CHANGE', '范围变更'), ('EXPIRE_EXTEND', '延期'), ('ROLE_CHANGE', '角色变更（同 scope 内升级/降级/平移，原子撤销旧角色+授予新角色）')], help_text='GRANT/REVOKE/SCOPE_CHANGE/EXPIRE_EXTEND/ROLE_CHANGE', max_length=16)),
                ('scope_type', models.CharField(choices=[('GLOBAL', '全局'), ('DEPT', '部门'), ('TEAM', '团队'), ('NONE', '无（全局角色）')], default='NONE', max_length=16)),
                ('scope_id', models.BigIntegerField(blank=True, help_text='dept_id 或 team_id（scope_type 对应）', null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='申请理由')),
                ('previous_role', models.ForeignKey(blank=True, help_text='角色变更工单的旧角色', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.role')),
                ('role', models.ForeignKey(blank=True, help_text='涉及角色（新角色/被撤销角色）', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.role')),
                ('target_user', models.ForeignKey(blank=True, help_text='被授权/被撤销对象', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='permission_detail', to='users.unifiedticket')),
            ],
            options={
                'verbose_name': '权限审批工单详情',
                'db_table': 'permission_ticket_detail',
            },
        ),
        # 注意：三张授权表的 ticket FK 从 PermissionApprovalTicket 改指向 UnifiedTicket，
        # 必须在存量授权引用清空、工单数据迁入统一主表之后执行（见 0010 迁移），
        # 否则 AlterField 重建外键时会因旧 ticket_id 在空表中无对应行而失败。
        migrations.AddIndex(
            model_name='unifiedticket',
            index=models.Index(fields=['biz_type', 'status'], name='uni_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedticket',
            index=models.Index(fields=['applicant', 'status'], name='uni_applicant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedticket',
            index=models.Index(fields=['status', 'created_at'], name='uni_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketflowlog',
            index=models.Index(fields=['ticket', 'created_at'], name='flow_log_ticket_created_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionticketdetail',
            index=models.Index(fields=['target_user'], name='permission__target__f09b02_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionticketdetail',
            index=models.Index(fields=['change_type'], name='permission__change__9cee04_idx'),
        ),
    ]
