# Generated by Django 5.2 on 2026-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_department_parent__30e6fa_idx_system_depa_parent__86ceb1_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_dept_name_active'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'department_id'), name='unique_team_name_per_dept_active'),
        ),
    ]
