# Generated by Django 5.2 on 2026-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_unique_dept_team_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
