# Generated by Django 5.2 on 2026-08-08 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_unifiedticket_updated_at'),
    ]

    operations = [
        # 统一工单主表改名：UnifiedTicket → TicketList，表名 unified_ticket → ticket_list
        # 先改表名再改模型名，保留 unified_ticket 表中的存量工单数据（开发期数据不丢）
        migrations.AlterModelTable(
            name='unifiedticket',
            table='ticket_list',
        ),
        migrations.RenameModel(
            old_name='UnifiedTicket',
            new_name='TicketList',
        ),
        migrations.RenameModel(
            old_name='PermissionTicketDetail',
            new_name='TicketPermissionDetail',
        ),
        migrations.AlterField(
            model_name='ticketflowlog',
            name='ticket',
            field=models.ForeignKey(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='flow_logs', to='users.ticketlist'),
        ),
        migrations.AlterField(
            model_name='ticketpermissiondetail',
            name='ticket',
            field=models.OneToOneField(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='permission_detail', to='users.ticketlist'),
        ),
        migrations.AlterField(
            model_name='userdeptscoperel',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_scope_rels', to='users.ticketlist'),
        ),
        migrations.AlterField(
            model_name='userrolerel',
            name='ticket',
            field=models.ForeignKey(blank=True, help_text='关联审批工单（有则填）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role_rels', to='users.ticketlist'),
        ),
        migrations.AlterField(
            model_name='userteamscoperel',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_scope_rels', to='users.ticketlist'),
        ),
        migrations.DeleteModel(
            name='PermissionApprovalTicket',
        ),
    ]
