# Generated by Django 5.2 on 2026-08-08 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_unifiedticket_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlist',
            name='applicant',
            field=models.ForeignKey(blank=True, help_text='发起人（权限工单=提单人；配置/模型工单=创建人）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_applied', to=settings.AUTH_USER_MODEL),
        ),
    ]
