# Generated by Django 5.2 on 2026-08-08 11:39

import django.db.models.deletion
from django.db import migrations, models


def _split_detail_to_subtables(apps, schema_editor):
    """将存量 ticket_list.detail JSON 拆分写入各类型详情子表

    主表 detail 字段移除前执行：config/schedule/model 工单的业务字段
    （config_label/old_value/new_value/change_summary、模型快照/变更字段/
    依赖清单、reason）按类型迁入对应的 OneToOne 详情子表。
    """
    TicketList = apps.get_model('users', 'TicketList')
    TicketConfigDetail = apps.get_model('users', 'TicketConfigDetail')
    TicketScheduleDetail = apps.get_model('users', 'TicketScheduleDetail')
    TicketModelDetail = apps.get_model('users', 'TicketModelDetail')
    for t in TicketList.objects.all().iterator(chunk_size=500):
        detail = t.detail if isinstance(t.detail, dict) else {}
        if t.biz_type == 'config':
            TicketConfigDetail.objects.create(
                ticket_id=t.id,
                config_label=detail.get('config_label', ''),
                old_value=detail.get('old_value', ''),
                new_value=detail.get('new_value', ''),
                change_summary=detail.get('change_summary', ''),
                reason=detail.get('reason', ''),
            )
        elif t.biz_type == 'schedule':
            TicketScheduleDetail.objects.create(
                ticket_id=t.id,
                config_label=detail.get('config_label', ''),
                old_value=detail.get('old_value', ''),
                new_value=detail.get('new_value', ''),
                change_summary=detail.get('change_summary', ''),
                reason=detail.get('reason', ''),
            )
        elif t.biz_type == 'model':
            TicketModelDetail.objects.create(
                ticket_id=t.id,
                target_model_snapshot=detail.get('target_model_snapshot', {}),
                changed_fields=detail.get('changed_fields', {}),
                dependency_refs=detail.get('dependency_refs', []),
                reason=detail.get('reason', ''),
            )


def _merge_subtables_to_detail(apps, schema_editor):
    """反向：回滚时把详情子表数据合并回主表 detail JSON（仅开发期回滚用）"""
    TicketList = apps.get_model('users', 'TicketList')
    TicketConfigDetail = apps.get_model('users', 'TicketConfigDetail')
    TicketScheduleDetail = apps.get_model('users', 'TicketScheduleDetail')
    TicketModelDetail = apps.get_model('users', 'TicketModelDetail')
    for t in TicketList.objects.all().iterator(chunk_size=500):
        detail = {}
        if t.biz_type == 'config':
            d = TicketConfigDetail.objects.filter(ticket_id=t.id).first()
            if d:
                detail = {
                    'config_label': d.config_label,
                    'old_value': d.old_value,
                    'new_value': d.new_value,
                    'change_summary': d.change_summary,
                    'reason': d.reason,
                }
        elif t.biz_type == 'schedule':
            d = TicketScheduleDetail.objects.filter(ticket_id=t.id).first()
            if d:
                detail = {
                    'config_label': d.config_label,
                    'old_value': d.old_value,
                    'new_value': d.new_value,
                    'change_summary': d.change_summary,
                    'reason': d.reason,
                }
        elif t.biz_type == 'model':
            d = TicketModelDetail.objects.filter(ticket_id=t.id).first()
            if d:
                detail = {
                    'target_model_snapshot': d.target_model_snapshot,
                    'changed_fields': d.changed_fields,
                    'dependency_refs': d.dependency_refs,
                    'reason': d.reason,
                }
        if detail:
            t.detail = detail
            t.save(update_fields=['detail'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_ticketlist_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketConfigDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_label', models.CharField(blank=True, default='', help_text='配置项显示名', max_length=128)),
                ('old_value', models.TextField(blank=True, default='', help_text='变更前值')),
                ('new_value', models.TextField(blank=True, default='', help_text='变更后值')),
                ('change_summary', models.TextField(blank=True, default='', help_text='差异摘要(JSON 字符串)')),
                ('reason', models.TextField(blank=True, default='', help_text='变更原因')),
                ('ticket', models.OneToOneField(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='config_detail', to='users.ticketlist')),
            ],
            options={
                'verbose_name': '配置变更工单详情',
                'db_table': 'config_ticket_detail',
            },
        ),
        migrations.CreateModel(
            name='TicketModelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model_snapshot', models.JSONField(blank=True, default=dict, help_text='创建工单时的模型快照（审计回溯用）')),
                ('changed_fields', models.JSONField(blank=True, default=dict, help_text='变更字段：{field: {old, new}}')),
                ('dependency_refs', models.JSONField(blank=True, default=list, help_text='依赖引用清单（停用/删除拦截用）')),
                ('reason', models.TextField(blank=True, default='', help_text='变更原因')),
                ('ticket', models.OneToOneField(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='model_detail', to='users.ticketlist')),
            ],
            options={
                'verbose_name': '模型变更工单详情',
                'db_table': 'model_ticket_detail',
            },
        ),
        migrations.CreateModel(
            name='TicketScheduleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_label', models.CharField(blank=True, default='', help_text='调度任务显示名', max_length=128)),
                ('old_value', models.TextField(blank=True, default='', help_text='变更前调度配置')),
                ('new_value', models.TextField(blank=True, default='', help_text='变更后调度配置')),
                ('change_summary', models.TextField(blank=True, default='', help_text='差异摘要(JSON 字符串)')),
                ('reason', models.TextField(blank=True, default='', help_text='变更原因')),
                ('ticket', models.OneToOneField(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_detail', to='users.ticketlist')),
            ],
            options={
                'verbose_name': '定时任务工单详情',
                'db_table': 'schedule_ticket_detail',
            },
        ),
        # 先回填子表再删主表 detail 列，保证存量数据不丢
        migrations.RunPython(_split_detail_to_subtables, _merge_subtables_to_detail),
        migrations.RemoveField(
            model_name='ticketlist',
            name='detail',
        ),
    ]
