# Generated by Django 5.2 on 2026-08-09 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_ticketlist_detail_ticketconfigdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlist',
            name='biz_type',
            field=models.CharField(choices=[('permission', '权限审批'), ('config', '配置变更'), ('model', '模型变更'), ('schedule', '定时任务'), ('agent', 'Agent审批')], db_index=True, max_length=16, verbose_name='工单类型'),
        ),
        migrations.CreateModel(
            name='TicketAgentApprovalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.BigIntegerField(db_index=True, help_text='Agent 工作流 ID')),
                ('node_id', models.CharField(help_text='待确认节点 ID', max_length=64)),
                ('reason', models.TextField(blank=True, default='', help_text='确认理由（前缀 [agent:{wf_id}:approval]）')),
                ('ticket', models.OneToOneField(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='agent_approval_detail', to='users.ticketlist')),
            ],
            options={
                'verbose_name': 'Agent 工作流人工确认工单详情',
                'db_table': 'agent_ticket_detail',
                'indexes': [models.Index(fields=['workflow_id'], name='idx_agent_detail_wf')],
            },
        ),
    ]
