# Generated by Django 5.2 on 2026-08-12 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_ticketlist_biz_type_ticketagentapprovaldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlist',
            name='biz_type',
            field=models.CharField(choices=[('permission', '权限审批'), ('config', '配置变更'), ('model', '模型变更'), ('schedule', '定时任务'), ('agent', 'Agent审批'), ('security', '安全配置')], db_index=True, max_length=16, verbose_name='工单类型'),
        ),
        migrations.CreateModel(
            name='TicketSecurityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_type', models.CharField(choices=[('ip_whitelist', 'IP白名单'), ('ip_blacklist', 'IP黑名单'), ('sensitive_word', '敏感词')], help_text='安全配置类型', max_length=32)),
                ('operation', models.CharField(choices=[('add', '新增'), ('edit', '编辑'), ('delete', '删除'), ('disable', '禁用')], help_text='操作类型', max_length=16)),
                ('target_data', models.JSONField(help_text='目标数据快照（如 ip/pattern/reason/category 等）')),
                ('old_data', models.JSONField(blank=True, help_text='变更前数据（编辑/删除时）', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='变更后数据（新增/编辑时）', null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='变更原因')),
                ('ticket', models.OneToOneField(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='security_detail', to='users.ticketlist')),
            ],
            options={
                'verbose_name': '安全配置工单详情',
                'db_table': 'security_ticket_detail',
                'indexes': [models.Index(fields=['security_type'], name='idx_sec_detail_type')],
            },
        ),
    ]
