# Generated by Django 5.2 on 2026-08-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_security_ticket_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlist',
            name='biz_type',
            field=models.CharField(choices=[('permission', '权限审批'), ('config', '配置变更'), ('model', '模型变更'), ('schedule', '定时任务'), ('agent', 'Agent审批'), ('security', '安全配置'), ('org', '组织变更')], db_index=True, max_length=16, verbose_name='工单类型'),
        ),
        migrations.CreateModel(
            name='TicketOrgDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(choices=[('dept', '部门'), ('team', '团队')], help_text='组织类型（部门/团队）', max_length=16)),
                ('operation', models.CharField(choices=[('add', '新增'), ('edit', '编辑'), ('delete', '删除')], help_text='操作类型', max_length=16)),
                ('target_data', models.JSONField(help_text='目标数据快照（如 id/name/code/description/department_id 等）')),
                ('old_data', models.JSONField(blank=True, help_text='变更前数据（编辑/删除时）', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='变更后数据（新增/编辑时）', null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='变更原因')),
                ('ticket', models.OneToOneField(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='org_detail', to='users.ticketlist')),
            ],
            options={
                'verbose_name': '组织变更工单详情',
                'db_table': 'org_ticket_detail',
                'indexes': [models.Index(fields=['org_type'], name='idx_org_detail_type')],
            },
        ),
    ]
