# Generated by Django 5.2 on 2026-08-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_ticketlist_biz_type_ticketorgdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlist',
            name='biz_type',
            field=models.CharField(choices=[('permission', '权限审批'), ('config', '配置变更'), ('model', '模型变更'), ('schedule', '定时任务'), ('agent', 'Agent审批'), ('security', '安全配置'), ('org', '组织变更'), ('role', '角色变更')], db_index=True, max_length=16, verbose_name='工单类型'),
        ),
        migrations.CreateModel(
            name='TicketRoleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', '新增角色'), ('edit', '编辑角色'), ('delete', '删除角色'), ('assign_perms', '角色权限分配')], help_text='操作类型（新增/编辑/删除/权限分配）', max_length=16)),
                ('old_data', models.JSONField(blank=True, help_text='变更前数据（编辑/删除时）', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='变更后数据（新增/编辑时）', null=True)),
                ('permission_ids', models.JSONField(blank=True, default=list, help_text='目标权限ID集合（权限分配时）')),
                ('reason', models.TextField(blank=True, default='', help_text='变更原因')),
                ('target_role', models.ForeignKey(blank=True, help_text='目标角色（新增时为 None）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.role')),
                ('ticket', models.OneToOneField(help_text='关联统一工单主表', on_delete=django.db.models.deletion.CASCADE, related_name='role_detail', to='users.ticketlist')),
            ],
            options={
                'verbose_name': '角色变更工单详情',
                'db_table': 'role_ticket_detail',
                'indexes': [models.Index(fields=['operation'], name='idx_role_detail_operation')],
            },
        ),
    ]
