# Generated by Django 5.2 on 2026-08-01 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField(default='')),
                ('category', models.CharField(default='system_notice', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sending', 'sending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_email_send_log',
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_esl_status')],
            },
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('feedback_reply', 'feedback_reply'), ('daily_report', 'daily_report'), ('system_notice', 'system_notice'), ('node_update', 'node_update'), ('keyword_alert', 'keyword_alert')], max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_email_subscription',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
