# Generated by Django 5.2 on 2026-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='category',
            field=models.CharField(choices=[('feedback_reply', 'feedback_reply'), ('daily_report', 'daily_report'), ('system_notice', 'system_notice'), ('node_update', 'node_update'), ('keyword_alert', 'keyword_alert')], max_length=32),
        ),
    ]
