# Generated by Django 5.2 on 2026-07-15 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_username', models.CharField(blank=True, default='', help_text='冗余：账号变名/删除时保留', max_length=64)),
                ('action', models.CharField(help_text='动作：login/upload_doc/delete_user...', max_length=64)),
                ('action_category', models.CharField(choices=[('auth', 'auth'), ('user', 'user'), ('rbac', 'rbac'), ('node', 'node'), ('document', 'document'), ('chat', 'chat'), ('config', 'config'), ('export', 'export'), ('security', 'security'), ('system', 'system')], default='system', max_length=16)),
                ('target_type', models.CharField(blank=True, default='', help_text='被操作对象类型 document/user/...', max_length=32)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('result', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('denied', 'denied')], default='success', max_length=16)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('path', models.CharField(blank=True, default='', max_length=256)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='详情快照，如 diff、error_message')),
                ('prev_hash', models.CharField(blank=True, default='', help_text='上一条 row_hash；首条为空串', max_length=64)),
                ('row_hash', models.CharField(blank=True, default='', help_text='本条 sha256', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['-created_at'], name='idx_al_time'), models.Index(fields=['actor', '-created_at'], name='idx_al_actor_time'), models.Index(fields=['action_category'], name='idx_al_category'), models.Index(fields=['target_type', 'target_id'], name='idx_al_target'), models.Index(fields=['action'], name='idx_al_action')],
            },
        ),
    ]
