# Generated by Django 5.2 on 2026-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(unique=True)),
                ('total_qa', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('bad_count', models.IntegerField(default=0)),
                ('no_feedback_count', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0, help_text='good / (good+bad)')),
                ('avg_latency_ms', models.IntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('top_bad_tags', models.JSONField(blank=True, default=list, help_text='[{tag, count}] 差评标签 Top 5')),
                ('top_root_types', models.JSONField(blank=True, default=list, help_text='[{root_type, qa_count}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_accuracy_report',
                'indexes': [models.Index(fields=['-report_date'], name='idx_ar_date')],
            },
        ),
        migrations.CreateModel(
            name='KeywordWeight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=64)),
                ('root_type', models.CharField(default='all', max_length=32)),
                ('hit_count', models.IntegerField(default=0)),
                ('good_feedback', models.IntegerField(default=0)),
                ('bad_feedback', models.IntegerField(default=0)),
                ('weight_score', models.FloatField(default=1.0, help_text='初始 1.0，好评 +0.1，差评 -0.1')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_keyword_weight',
                'indexes': [models.Index(fields=['keyword'], name='idx_kw_kw'), models.Index(fields=['-weight_score'], name='idx_kw_score')],
                'unique_together': {('keyword', 'root_type')},
            },
        ),
    ]
