# Generated by Django 5.2 on 2026-07-30 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('chat', '0002_add_qa_ttfb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUsageReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('department_name', models.CharField(default='', max_length=64)),
                ('team_id', models.IntegerField(blank=True, help_text='NULL 表示部门级汇总（含所有子团队）', null=True)),
                ('team_name', models.CharField(default='', max_length=64)),
                ('qa_count', models.IntegerField(default=0)),
                ('user_count', models.IntegerField(default=0, help_text='当日活跃用户数（distinct）')),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('avg_latency_ms', models.IntegerField(default=0)),
                ('p95_latency_ms', models.IntegerField(default=0, help_text='该组织请求的 P95 延迟（Python 排序计算）')),
                ('good_feedback_rate', models.FloatField(default=0.0, help_text='好评率（有反馈的请求中）')),
                ('cache_hit_count', models.IntegerField(default=0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_org_usage_report',
                'indexes': [models.Index(fields=['-report_date'], name='analytics_o_report__55ed32_idx'), models.Index(fields=['department_id', 'team_id'], name='analytics_o_departm_0998c1_idx')],
                'unique_together': {('report_date', 'department_id', 'team_id')},
            },
        ),
        migrations.CreateModel(
            name='QueueDepthLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('queue_name', models.CharField(help_text='队列名: default / document_parse / embedding / llm', max_length=64)),
                ('depth', models.IntegerField(default=0, help_text='待处理任务数（Redis LLEN 查询结果）')),
                ('worker_count', models.IntegerField(default=0, help_text='活跃 Worker 数（Celery inspect API 获取）')),
                ('avg_wait_sec', models.FloatField(default=0.0, help_text='队列任务平均等待时间（估算值，后续可扩展）')),
                ('task_types', models.JSONField(default=list, help_text='队列中各类型任务计数（后续扩展）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_queue_depth_log',
                'indexes': [models.Index(fields=['queue_name', '-created_at'], name='idx_qdl_queue_time'), models.Index(fields=['-created_at'], name='idx_qdl_time')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetricsReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(unique=True)),
                ('total_qa', models.IntegerField(default=0)),
                ('cache_hit_count', models.IntegerField(default=0, help_text='缓存命中数')),
                ('normal_qa_count', models.IntegerField(default=0, help_text='非缓存请求数')),
                ('p50_latency_total', models.IntegerField(default=0, help_text='端到端 P50（不含缓存命中）')),
                ('p95_latency_total', models.IntegerField(default=0, help_text='端到端 P95（不含缓存命中）')),
                ('p99_latency_total', models.IntegerField(default=0, help_text='端到端 P99（不含缓存命中）')),
                ('p50_latency_llm', models.IntegerField(default=0, help_text='LLM 调用 P50')),
                ('p95_latency_llm', models.IntegerField(default=0, help_text='LLM 调用 P95')),
                ('p50_latency_retrieval', models.IntegerField(default=0, help_text='检索 P50')),
                ('p95_latency_retrieval', models.IntegerField(default=0, help_text='检索 P95')),
                ('p50_ttfb', models.IntegerField(default=0, help_text='首字返回 P50')),
                ('p95_ttfb', models.IntegerField(default=0, help_text='首字返回 P95')),
                ('cache_hit_p50_latency', models.IntegerField(default=0, help_text='缓存命中请求 P50 延迟')),
                ('cache_hit_p95_latency', models.IntegerField(default=0, help_text='缓存命中请求 P95 延迟')),
                ('cache_hit_rate', models.FloatField(default=0.0, help_text='缓存命中率')),
                ('llm_success_rate', models.FloatField(default=0.0, help_text='LLM 成功率（仅统计非缓存请求）')),
                ('llm_timeout_rate', models.FloatField(default=0.0, help_text='LLM 超时率')),
                ('embedding_error_rate', models.FloatField(default=0.0, help_text='Embedding 错误率')),
                ('avg_tokens_per_second', models.FloatField(default=0.0, help_text='Token 生成速率（仅非缓存请求）')),
                ('total_tokens_prompt', models.BigIntegerField(default=0)),
                ('total_tokens_completion', models.BigIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('latency_histogram', models.JSONField(blank=True, default=dict, help_text='{区间: 计数} 示例: {"0-100": 123, "100-200": 456}')),
                ('error_distribution', models.JSONField(blank=True, default=dict, help_text='{错误类型: 计数} 示例: {"timeout": 5, "network": 2}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_system_metrics_report',
                'indexes': [models.Index(fields=['-report_date'], name='idx_smr_date')],
            },
        ),
        migrations.CreateModel(
            name='AnswerQualityReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('faithfulness_score', models.FloatField(default=0.0, help_text='忠实度 0-1（分数越高表示回答越忠实于原文）')),
                ('faithfulness_reason', models.TextField(default='', help_text='评估理由（中文，便于运营直接阅读）')),
                ('eval_model', models.CharField(help_text='使用的评估模型', max_length=64)),
                ('eval_tokens_used', models.IntegerField(default=0)),
                ('eval_cost', models.DecimalField(decimal_places=6, default=0, help_text='本次评估消耗费用（元）', max_digits=8)),
                ('eval_latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '待评估'), ('completed', '已完成'), ('failed', '失败（可重试）')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0, help_text='失败重试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qa_record', models.OneToOneField(db_column='qa_record_id', on_delete=django.db.models.deletion.CASCADE, related_name='quality_report', to='chat.qarecord')),
            ],
            options={
                'db_table': 'analytics_answer_quality_report',
                'indexes': [models.Index(fields=['-created_at'], name='idx_aqr_time'), models.Index(fields=['status', '-created_at'], name='idx_aqr_status_time'), models.Index(fields=['faithfulness_score'], name='idx_aqr_score')],
            },
        ),
    ]
