# Generated by Django 5.2 on 2026-08-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multidimensionscore',
            name='dimension',
            field=models.CharField(choices=[('faithfulness', '忠实度'), ('answer_relevancy', '相关性'), ('context_relevancy', '上下文相关性'), ('hallucination', '幻觉'), ('toxicity', '毒性'), ('bias', '偏见'), ('completeness', '完整性'), ('conciseness', '简洁性'), ('clarity', '清晰度'), ('professionalism', '专业性'), ('helpfulness', '有用性'), ('actionability', '可操作性'), ('relevance', '相关性(自研)'), ('correctness', '正确性(自研)'), ('harmlessness', '无害性(自研)'), ('context_recall', '上下文召回率(自研)')], max_length=20),
        ),
    ]
