# Generated by Django 5.2 on 2026-08-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_multidimensionscore_dimension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerQualityReport',
        ),
    ]
