# Generated by Django 5.2 on 2026-07-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_orgusagereport_queuedepthlog_systemmetricsreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgusagereport',
            name='team_id',
            field=models.IntegerField(default=-1, help_text='-1=部门级汇总（含所有子团队），>=0=具体团队 ID'),
        ),
        migrations.AlterField(
            model_name='queuedepthlog',
            name='queue_name',
            field=models.CharField(help_text='队列名: default / parse / memory / email / analytics', max_length=64),
        ),
    ]
