# Generated by Django 5.2 on 2026-08-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_answer_quality_report'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowScoreAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avg_score', models.FloatField(default=0.0, help_text='触发归因时的 QA 12 维均分')),
                ('threshold', models.FloatField(default=0.5, help_text='触发归因的阈值')),
                ('root_cause_category', models.CharField(choices=[('retrieval_recall', '检索召回不足'), ('retrieval_rank', '检索排序失效'), ('content_gap', '知识盲区'), ('content_quality', '内容质量差'), ('generation_hallucination', '生成幻觉'), ('generation_offtopic', '生成跑题'), ('generation_incomplete', '生成不完整'), ('generation_format', '生成表达差'), ('safety', '安全问题'), ('question_side', '问题侧'), ('unknown', '无法归因')], default='unknown', max_length=32)),
                ('root_cause_detail', models.TextField(blank=True, default='', help_text='具体原因描述(规则命中条件 / LLM 诊断)')),
                ('affected_layer', models.CharField(choices=[('retrieval', '检索层'), ('content', '内容层'), ('generation', '生成层'), ('safety', '安全层'), ('system', '系统层'), ('question', '问题侧'), ('unknown', '未知')], default='unknown', max_length=16)),
                ('low_dimensions', models.JSONField(blank=True, default=list, help_text='[{"dimension":"faithfulness","score":0.32,"reason":"..."}]')),
                ('diagnosis', models.TextField(blank=True, default='', help_text='一句话诊断(LLM 生成,模板归因为空)')),
                ('suggestions', models.JSONField(blank=True, default=list, help_text='[{"type":"short_term","action":"..."},{"type":"long_term","action":"..."}]')),
                ('analysis_method', models.CharField(choices=[('rule', '规则归因'), ('llm', 'LLM 归因'), ('hybrid', '规则+LLM')], default='rule', max_length=16)),
                ('analysis_model', models.CharField(blank=True, default='', max_length=64)),
                ('analysis_tokens_used', models.IntegerField(default=0)),
                ('analysis_cost', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('analysis_latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '待分析'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='', help_text='失败原因(status=failed 时填充)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qa_record', models.OneToOneField(db_column='qa_record_id', on_delete=django.db.models.deletion.CASCADE, related_name='low_score_analysis', to='chat.qarecord')),
            ],
            options={
                'db_table': 'analytics_low_score_analysis',
                'indexes': [models.Index(fields=['-created_at'], name='idx_lsa_time'), models.Index(fields=['root_cause_category', '-created_at'], name='idx_lsa_cat_time'), models.Index(fields=['status', '-created_at'], name='idx_lsa_status_time')],
            },
        ),
    ]
