# Generated by Django 5.2 on 2026-07-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_orgusagereport_team_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedepthlog',
            name='minute_bucket',
            field=models.DateTimeField(blank=True, help_text='快照时间截断到分钟（用于唯一约束防重复）', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='queuedepthlog',
            unique_together={('queue_name', 'minute_bucket')},
        ),
    ]
