# Generated by Django 5.2 on 2026-08-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_golden_dataset_type_and_regression_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldendataset',
            name='root_type',
            field=models.CharField(default='company_doc', help_text='测试集覆盖的领域', max_length=32),
        ),
    ]
