# Generated by Django 5.2 on 2026-08-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_goldendataset_root_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('route_source', models.CharField(db_index=True, max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('route_trace', models.JSONField(blank=True, default=list)),
                ('latency_ms', models.IntegerField(default=0)),
                ('answer_quality', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'analytics_route',
                'indexes': [models.Index(fields=['route_source', 'created_at'], name='idx_ar_source_time')],
            },
        ),
    ]
