# Generated by Django 5.2 on 2026-08-06 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_routeanalysis'),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPageQualityScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('faithfulness', '忠实度'), ('completeness', '完整性')], max_length=32)),
                ('score', models.FloatField(default=0.0, help_text='0-1 分')),
                ('reason', models.TextField(blank=True, default='', help_text='评估理由')),
                ('eval_model', models.CharField(default='deepseek-chat', max_length=64)),
                ('eval_latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', '已完成'), ('failed', '失败')], default='completed', max_length=16)),
                ('error_message', models.TextField(blank=True, default='', help_text='失败原因(status=failed 时填充)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_wiki_page_quality_score',
            },
        ),
        migrations.AddField(
            model_name='routeanalysis',
            name='qa_record_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='来源 QaRecord.id，聚合幂等键', null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='routeanalysis',
            index=models.Index(fields=['created_at', 'route_source'], name='idx_ar_time_source'),
        ),
        migrations.AddField(
            model_name='wikipagequalityscore',
            name='page',
            field=models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='quality_scores', to='wiki.wikipage'),
        ),
        migrations.AddIndex(
            model_name='wikipagequalityscore',
            index=models.Index(fields=['page', 'dimension'], name='idx_wpqs_page_dim'),
        ),
        migrations.AddIndex(
            model_name='wikipagequalityscore',
            index=models.Index(fields=['-updated_at'], name='idx_wpqs_time'),
        ),
        migrations.AlterUniqueTogether(
            name='wikipagequalityscore',
            unique_together={('page', 'dimension')},
        ),
    ]
