# Generated by Django 5.2 on 2026-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_wikipagequalityscore_routeanalysis_qa_record_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeanalysis',
            name='qa_created_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='来源 QaRecord.created_at，看板时间窗口过滤键', null=True),
        ),
    ]
