# Generated by Django 5.2 on 2026-08-09 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_routeanalysis_qa_created_at'),
        ('chat', '0003_alter_hotqacache_visibility_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkClickLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_id', models.BigIntegerField(blank=True, help_text='被点击引用对应的文档 ID', null=True)),
                ('chunk_id', models.BigIntegerField(help_text='被点击的 chunk id')),
                ('root_type', models.CharField(default='all', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('qa_record', models.ForeignKey(blank=True, db_column='qa_record_id', help_text='被点击回答对应的 QaRecord.id（前端从流式 done 事件回填）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunk_click_logs', to='chat.qarecord')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunk_click_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_chunk_click_log',
                'indexes': [models.Index(fields=['qa_record_id', 'chunk_id'], name='idx_ccl_qa_chunk'), models.Index(fields=['-created_at'], name='idx_ccl_time')],
            },
        ),
        migrations.CreateModel(
            name='KeywordFeedbackAgg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(help_text='聚合日期（业务日期）')),
                ('keyword', models.CharField(max_length=64)),
                ('root_type', models.CharField(default='all', max_length=32)),
                ('shown_count', models.IntegerField(default=0, help_text='关键词命中 chunk 的展示次数（retrieval_hits）')),
                ('click_count', models.IntegerField(default=0, help_text='展示后被点击的次数')),
                ('adopt_count', models.IntegerField(default=0, help_text='展示并被回答引用的次数（citations 命中）')),
                ('bad_count', models.IntegerField(default=0, help_text='含该关键词的差评对话数')),
                ('click_rate', models.FloatField(default=0.0, help_text='点击率 = click/shown')),
                ('adopt_rate', models.FloatField(default=0.0, help_text='采纳率 = adopt/shown')),
                ('old_score', models.FloatField(default=1.0, help_text='调整前权重')),
                ('new_score', models.FloatField(default=1.0, help_text='调整后权重（未应用时为目标值）')),
                ('delta', models.FloatField(default=0.0, help_text='本次调整幅度（受单日上限保护）')),
                ('reason', models.CharField(blank=True, default='', help_text='调整原因（规则命中说明，如 采纳率低/点击未采纳/负反馈）', max_length=128)),
                ('adjust_type', models.CharField(choices=[('auto', '自动'), ('manual', '手动')], default='auto', max_length=16)),
                ('status', models.CharField(choices=[('pending', '待复核'), ('applied', '已应用'), ('ignored', '已忽略')], default='pending', max_length=16)),
                ('applied_at', models.DateTimeField(blank=True, help_text='权重实际生效时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, db_column='actor_id', help_text='操作人（手动调整时必填，自动调整为系统）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyword_feedback_aggs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_keyword_feedback_agg',
                'indexes': [models.Index(fields=['report_date', 'root_type'], name='idx_kfa_date_root'), models.Index(fields=['keyword'], name='idx_kfa_keyword'), models.Index(fields=['status', '-created_at'], name='idx_kfa_status_time')],
                'unique_together': {('report_date', 'keyword', 'root_type')},
            },
        ),
    ]
