# Generated by Django 5.2 on 2026-08-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_chunkclicklog_keywordfeedbackagg'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetricsreport',
            name='cache_hit_p99_latency',
            field=models.IntegerField(default=0, help_text='缓存命中请求 P99 延迟'),
        ),
        migrations.AddField(
            model_name='systemmetricsreport',
            name='p99_latency_llm',
            field=models.IntegerField(default=0, help_text='LLM 调用 P99'),
        ),
        migrations.AddField(
            model_name='systemmetricsreport',
            name='p99_latency_retrieval',
            field=models.IntegerField(default=0, help_text='检索 P99'),
        ),
        migrations.AddField(
            model_name='systemmetricsreport',
            name='p99_ttfb',
            field=models.IntegerField(default=0, help_text='首字返回 P99'),
        ),
    ]
