# Generated by Django 5.2 on 2026-07-15 12:34

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotQaCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_hash', models.CharField(help_text='sha256(normalized_question)', max_length=64)),
                ('root_type', models.CharField(max_length=32)),
                ('visibility_scope', models.CharField(default='public', help_text='public/team/private', max_length=16)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hot_qa_cache',
                'indexes': [models.Index(fields=['-hit_count'], name='idx_hot_hits')],
                'unique_together': {('question_hash', 'root_type', 'visibility_scope')},
            },
        ),
        migrations.CreateModel(
            name='QaRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('turn_index', models.IntegerField(default=0, help_text='会话内轮次')),
                ('question', models.TextField(help_text='用户原始问题')),
                ('question_tokens', models.IntegerField(default=0)),
                ('retrieval_hits', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, help_text='命中的 document_chunk.id', size=None)),
                ('retrieval_scores', models.JSONField(blank=True, default=list, help_text='[{chunk_id,vector,bm25,rrf,rerank}]')),
                ('root_type', models.CharField(default='company_doc', help_text='本次问答的根类型（选定的知识库）', max_length=32)),
                ('answer', models.TextField(default='')),
                ('answer_type', models.CharField(choices=[('rag', 'rag'), ('reasoning', 'reasoning'), ('mixed', 'mixed'), ('refused', 'refused')], default='rag', max_length=16)),
                ('answer_tokens', models.IntegerField(default=0)),
                ('citations', models.JSONField(blank=True, default=list, help_text='[{chunk_id,doc_title,section,page}]')),
                ('latency_retrieval_ms', models.IntegerField(default=0)),
                ('latency_rerank_ms', models.IntegerField(default=0)),
                ('latency_llm_ms', models.IntegerField(default=0)),
                ('latency_total_ms', models.IntegerField(default=0)),
                ('tokens_prompt', models.IntegerField(default=0)),
                ('tokens_completion', models.IntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('llm_provider', models.CharField(default='deepseek', max_length=32)),
                ('llm_model', models.CharField(default='deepseek-chat', max_length=64)),
                ('is_hit_cache', models.BooleanField(default=False, help_text='是否命中热点缓存')),
                ('is_task_split', models.BooleanField(default=False, help_text='是否触发复杂任务拆分')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='qa_records', to='memory.session')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qa_record',
            },
        ),
        migrations.CreateModel(
            name='QaFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField(default=0, help_text='1好评 -1差评 0中性')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='差评原因标签：不准确/无引用/回答慢...', size=None)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('resolved', 'resolved'), ('ignored', 'ignored')], default='pending', max_length=16)),
                ('admin_reply', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('qa_record', models.OneToOneField(db_column='qa_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.qarecord')),
            ],
            options={
                'db_table': 'qa_feedback',
            },
        ),
        migrations.CreateModel(
            name='TaskDecomposition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_question', models.TextField()),
                ('sub_tasks', models.JSONField(default=list, help_text='[{index,question,dep,answer}]')),
                ('merged_answer', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planning', 'planning'), ('executing', 'executing'), ('merging', 'merging'), ('done', 'done'), ('failed', 'failed')], default='planning', max_length=16)),
                ('total_latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qa_record', models.OneToOneField(db_column='qa_id', on_delete=django.db.models.deletion.CASCADE, related_name='decomposition', to='chat.qarecord')),
            ],
            options={
                'db_table': 'task_decomposition',
            },
        ),
        migrations.AddIndex(
            model_name='qarecord',
            index=models.Index(fields=['session', 'turn_index'], name='idx_qa_sess_turn'),
        ),
        migrations.AddIndex(
            model_name='qarecord',
            index=models.Index(fields=['user', '-created_at'], name='idx_qa_user_time'),
        ),
        migrations.AddIndex(
            model_name='qarecord',
            index=models.Index(fields=['root_type'], name='idx_qa_root'),
        ),
        migrations.AddIndex(
            model_name='qarecord',
            index=models.Index(fields=['answer_type'], name='idx_qa_ans_type'),
        ),
        migrations.AddIndex(
            model_name='qafeedback',
            index=models.Index(fields=['status', '-created_at'], name='idx_fb_status_time'),
        ),
        migrations.AddIndex(
            model_name='qafeedback',
            index=models.Index(fields=['rating'], name='idx_fb_rating'),
        ),
    ]
