# Generated by Django 5.2 on 2026-07-22 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('memory', '0002_alter_globalmemory_table_alter_session_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qafeedback',
            index=models.Index(fields=['-created_at'], name='idx_fb_created'),
        ),
        migrations.AddIndex(
            model_name='qarecord',
            index=models.Index(fields=['-created_at'], name='idx_qa_created'),
        ),
    ]
