# Generated by Django 5.2 on 2026-08-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='route_source',
            field=models.CharField(blank=True, help_text='路由来源: wiki/graphrag_local/graphrag_global/rag/agent', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='qarecord',
            name='route_trace',
            field=models.JSONField(blank=True, help_text='路由决策追踪日志（每层置信度与耗时）', null=True),
        ),
    ]
