# Generated by Django 5.2 on 2026-07-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='latency_ttfb_ms',
            field=models.IntegerField(default=0, help_text='首字返回耗时（请求起点→首个 delta，ms）'),
        ),
    ]
