# Generated by Django 5.2 on 2026-08-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_qarecord_route_source_qarecord_route_trace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotqacache',
            name='visibility_scope',
            field=models.CharField(default='public', help_text='缓存权限组：public / org_d3_t7（组织分组）', max_length=64),
        ),
    ]
