# Generated by Django 5.2 on 2026-07-30 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_qa_ttfb'),
        ('memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='error_type',
            field=models.CharField(blank=True, choices=[('timeout', 'timeout'), ('rate_limit', 'rate_limit'), ('network', 'network'), ('content_filter', 'content_filter'), ('server_error', 'server_error'), ('embedding_error', 'embedding_error'), ('unknown', 'unknown')], default='', help_text='错误类型：timeout/rate_limit/network/content_filter/server_error/embedding_error', max_length=32),
        ),
        migrations.AddField(
            model_name='qarecord',
            name='is_success',
            field=models.BooleanField(default=True, help_text='对话是否成功完成（False=链路中断）'),
        ),
        migrations.AddField(
            model_name='qarecord',
            name='tokens_per_second',
            field=models.FloatField(default=0.0, help_text='生成速率: completion_tokens / llm_duration_sec'),
        ),
        migrations.AddIndex(
            model_name='qarecord',
            index=models.Index(fields=['is_success', '-created_at'], name='idx_qa_success_time'),
        ),
        migrations.AddIndex(
            model_name='qarecord',
            index=models.Index(fields=['error_type', '-created_at'], name='idx_qa_errtype_time'),
        ),
    ]
