# Generated by Django 5.2 on 2026-07-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_qarecord_error_type_qarecord_is_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='filter_reason',
            field=models.CharField(blank=True, default='', help_text='命中原因：敏感词分类或命中词列表（审计用）', max_length=128),
        ),
        migrations.AddField(
            model_name='qarecord',
            name='is_filtered',
            field=models.BooleanField(default=False, help_text='是否命中敏感词审查（block/mask）'),
        ),
    ]
