# Generated by Django 5.2 on 2026-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_hotqacache_visibility_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qarecord',
            name='answer_type',
            field=models.CharField(choices=[('rag', 'rag'), ('reasoning', 'reasoning'), ('mixed', 'mixed'), ('refused', 'refused'), ('agent', 'agent'), ('general', 'general')], default='rag', max_length=16),
        ),
    ]
