# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_qarecord_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标记（用户撤回/删除消息）'),
        ),
    ]
