# Generated by Django 5.2 on 2026-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_qarecord_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qarecord',
            name='answer_type',
            field=models.CharField(choices=[('rag', 'rag'), ('reasoning', 'reasoning'), ('mixed', 'mixed'), ('refused', 'refused'), ('agent', 'agent'), ('general', 'general'), ('plan', 'plan')], default='rag', max_length=16),
        ),
    ]
