# Generated by Django 5.2 on 2026-08-01 13:10

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        # 依赖 pgvector 扩展安装迁移：DocumentVector 含 vector 字段，
        # 必须先于 users.0007_install_pgvector 之后的表创建（否则新库建表失败）
        ('users', '0007_install_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVector',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, help_text='BGE-M3 向量，1024 维')),
                ('visibility_level', models.CharField(choices=[('TEAM_ONLY', '仅团队'), ('DEPT_ONLY', '仅部门'), ('PUBLIC', '全局公开')], default='TEAM_ONLY', help_text='冗余：TEAM_ONLY/DEPT_ONLY/PUBLIC', max_length=32)),
                ('dept_id', models.BigIntegerField(blank=True, help_text='冗余：归属部门 ID', null=True)),
                ('team_id', models.BigIntegerField(blank=True, help_text='冗余：归属团队 ID', null=True)),
                ('owner_id', models.BigIntegerField(help_text='冗余：文档 Owner user_id')),
                ('root_type', models.CharField(help_text='冗余：根节点类型', max_length=32)),
                ('node_id', models.BigIntegerField(help_text='冗余：挂载节点 ID')),
                ('node_path', models.CharField(default='/', help_text='冗余：节点路径，支持前缀过滤（节点级共享继承）', max_length=512)),
                ('has_resource_share', models.BooleanField(default=False, help_text='冗余：是否有跨范围共享')),
                ('has_block_user', models.BooleanField(default=False, help_text='冗余：是否有黑名单用户')),
                ('chunk_type', models.CharField(default='text', help_text='冗余：切片类型，方便按类型过滤', max_length=16)),
                ('content_preview', models.TextField(default='', help_text='切片前 200 字，用于快速展示')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='jieba 分词后的关键词，加速 BM25', size=None)),
                ('embedding_model', models.CharField(default='bge-m3', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(db_column='chunk_id', on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='knowledge.documentchunk')),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='knowledge.document')),
            ],
            options={
                'db_table': 'retrieval_doc_vector',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_dv_embedding_hnsw', opclasses=['vector_cosine_ops']), models.Index(fields=['visibility_level', 'root_type'], name='idx_dv_vis_root'), models.Index(fields=['owner_id'], name='idx_dv_owner'), models.Index(fields=['team_id'], name='idx_dv_team'), models.Index(fields=['dept_id'], name='idx_dv_dept'), models.Index(fields=['node_id'], name='idx_dv_node'), models.Index(fields=['node_path'], name='idx_dv_path'), models.Index(fields=['document'], name='idx_dv_doc')],
            },
        ),
    ]
