# Generated by Django 5.2 on 2026-07-25 08:40

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVector',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, help_text='BGE-M3 向量，1024 维')),
                ('visible_scope', models.CharField(default='team', help_text='冗余：team/dept/public', max_length=16)),
                ('has_cross_team', models.BooleanField(default=False, help_text='冗余：是否有跨团队授权')),
                ('has_allow_user', models.BooleanField(default=False, help_text='冗余：是否有个人白名单')),
                ('owner_id', models.BigIntegerField(help_text='冗余：文档拥有者 user_id')),
                ('team_node_id', models.BigIntegerField(blank=True, help_text='冗余：归属团队节点 id', null=True)),
                ('dept_node_id', models.BigIntegerField(blank=True, help_text='冗余：归属部门节点 id', null=True)),
                ('root_type', models.CharField(help_text='冗余：根节点类型', max_length=32)),
                ('node_id', models.BigIntegerField(help_text='冗余：所属叶子节点 id')),
                ('node_path', models.CharField(default='/', help_text='冗余：节点路径，支持前缀过滤', max_length=512)),
                ('chunk_type', models.CharField(default='text', help_text='冗余：切片类型，方便按类型过滤', max_length=16)),
                ('content_preview', models.TextField(default='', help_text='切片前 200 字，用于快速展示')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='jieba 分词后的关键词，加速 BM25', size=None)),
                ('embedding_model', models.CharField(default='bge-m3', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(db_column='chunk_id', on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='knowledge.documentchunk')),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='knowledge.document')),
            ],
            options={
                'db_table': 'retrieval_doc_vector',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_dv_embedding_hnsw', opclasses=['vector_cosine_ops']), models.Index(fields=['visible_scope', 'root_type'], name='idx_dv_vis_root'), models.Index(fields=['owner_id'], name='idx_dv_owner'), models.Index(fields=['team_node_id'], name='idx_dv_team'), models.Index(fields=['dept_node_id'], name='idx_dv_dept'), models.Index(fields=['node_id'], name='idx_dv_node'), models.Index(fields=['node_path'], name='idx_dv_path'), models.Index(fields=['document'], name='idx_dv_doc')],
            },
        ),
    ]
