# Generated by Django 5.2 on 2026-08-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvector',
            name='is_active',
            field=models.BooleanField(default=True, help_text='冗余：文档是否活跃版本（检索只召回活跃版本，由 vector_store 同步）'),
        ),
    ]
