# Generated by Django 5.2 on 2026-07-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentvector',
            table='vector_document_vector',
        ),
    ]
