# Generated by Django 5.2 on 2026-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0002_alter_documentvector_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvector',
            name='owner_department_id',
            field=models.BigIntegerField(blank=True, help_text='冗余：上传者部门快照 id', null=True),
        ),
        migrations.AlterField(
            model_name='documentvector',
            name='visibility',
            field=models.SmallIntegerField(default=1, help_text='1私有 2部门 3团队 4公开'),
        ),
    ]
