# Generated by Django 5.2 on 2026-08-13 14:35

from django.db import migrations, models


def backfill_audit_status(apps, schema_editor):
    """存量向量按所属文档的审核状态回填 audit_status

    新列默认 pending_team，若不回填则所有存量向量（含已双审通过的文档）
    都会被检索层的 audit_status='passed' 过滤掉，导致历史可检索数据全部失效。
    """
    DocumentVector = apps.get_model('retrieval', 'DocumentVector')
    DocumentVector.objects.filter(document__audit_status='passed').update(audit_status='passed')


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0002_documentvector_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvector',
            name='audit_status',
            field=models.CharField(default='pending_team', help_text='冗余：文档审核状态（检索只召回双审通过 passed，由 vector_store/审核流程同步）', max_length=32),
        ),
        migrations.RunPython(backfill_audit_status, migrations.RunPython.noop),
    ]
